### ISSUE TITLE
<b>Fatal error</b>:  Uncaught Error: Call to undefined function get_remote_ip() in /web/inc/sessions.inc.php:37

### ISSUE THREAD

**Issue by extremeshok** [mailcow/mailcow-dockerized#1640]
Latest update, when doing a remote api call to : /api/v1/add/mailbox
````ERROR: <br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function get_remote_ip() in /web/inc/sessions.inc.php:37
Stack trace:
#0 /web/inc/prerequisites.inc.php(55): require_once()
#1 /web/json_api.php(16): require_once('/web/inc/prereq...')
#2 {main}
  thrown in <b>/web/inc/sessions.inc.php</b> on line <b>37</b><br />
ERROR: <br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function get_remote_ip() in /web/inc/sessions.inc.php:37
Stack trace:
#0 /web/inc/prerequisites.inc.php(55): require_once()
#1 /web/json_api.php(16): require_once('/web/inc/prereq...')
#2 {main}
  thrown in <b>/web/inc/sessions.inc.php</b> on line <b>37</b><br />
````

**Comment by andryyy** [comment]
Thanks, will fix it asap.
