### ISSUE TITLE
Docker compose issue after update to latest version

### ISSUE THREAD

**Issue by next-direction** [mailcow/mailcow-dockerized#230]
Hello,

today I updated mailcow like described in the install section of the docs.

The second command of the second step couldn't be finished and produced the following error message:

<host>:~/mailcow-dockerized# docker-compose up -d
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 68, in main
  File "compose/cli/main.py", line 118, in perform_command
  File "compose/cli/main.py", line 924, in up
  File "compose/project.py", line 389, in up
  File "compose/project.py", line 437, in initialize
  File "compose/network.py", line 252, in initialize
  File "compose/network.py", line 60, in ensure
  File "compose/network.py", line 180, in check_remote_network_config
  File "compose/network.py", line 163, in check_remote_ipam_config
AttributeError: 'NoneType' object has no attribute 'keys'
Failed to execute script docker-compose

I restarted the containers with "docker-compose restart" and everything seems ok but I want to ask if this error message can make any problems in the future.

Thanks.

**Comment by andryyy** [comment]
Hi,

I guess you pulled v1.13rc of docker-compose to your server. The script @ https://www.servercow.de/docker-compose/latest.php downloaded pre-releases, which is now fixed.

Please just downgrade to 1.12 stable and you'll be fine. :)

**Comment by next-direction** [comment]
Hi,

thanks, that was the problem. I close the issue ;-)
