### ISSUE TITLE
Docker won't come up after upgrade

### ISSUE THREAD

**Issue by Lucky88888** [mailcow/mailcow-dockerized#2871]
Anybody, any clue what is going wrong here? Please let me know which other details I should provide. 

After I did an ./update.sh the script was giving an error on failing clam module. So I did the update again. After that no responding system so I gave it a reboot. No I am not able to get docker running again. 

```
# systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since ma 2019-08-19 16:53:14 CEST; 15s ago
     Docs: https://docs.docker.com
  Process: 16424 ExecStart=/usr/bin/dockerd (code=exited, status=2)
 Main PID: 16424 (code=exited, status=2)
    Tasks: 77
   Memory: 69.4M
   CGroup: /system.slice/docker.service
           ├─ 5215 docker-containerd-shim 6902fc362e8ea960e65b10f7cde9820c94d3596f3ad4523c6c06fe415b72f037 /var/run/docker/libcontainerd/6902fc362e8ea960e65b10f7cde9820c94d3596f3ad4523c6c06fe415b72f037...
           ├─ 5222 docker-containerd-shim 4c1801df95bef712bba6dbcb535bb85f6b6b077dc91e7f1d56fc88189736ce2f /var/run/docker/libcontainerd/4c1801df95bef712bba6dbcb535bb85f6b6b077dc91e7f1d56fc88189736ce2f...
           ├─ 7182 docker-containerd-shim a505a4aaf405e521d248de633abe8a0b20e19982164b0026de81a27ffe5ff73a /var/run/docker/libcontainerd/a505a4aaf405e521d248de633abe8a0b20e19982164b0026de81a27ffe5ff73a...
           ├─ 7694 docker-containerd-shim a7e40b5226851a2010ab9afb3a541e39b5b53861753c46506b7ec1abb1896d45 /var/run/docker/libcontainerd/a7e40b5226851a2010ab9afb3a541e39b5b53861753c46506b7ec1abb1896d45...
           ├─ 9058 docker-containerd-shim ee64f5223212ec458d40275a2289330cd0d64efa66c8d222dc98fecc23672565 /var/run/docker/libcontainerd/ee64f5223212ec458d40275a2289330cd0d64efa66c8d222dc98fecc23672565...
           ├─11258 docker-containerd-shim ea12e17a02f7a927b8da20925ebb2f562cdd12dc9441f6186a05c47453ee310a /var/run/docker/libcontainerd/ea12e17a02f7a927b8da20925ebb2f562cdd12dc9441f6186a05c47453ee310a...
           ├─11285 docker-containerd-shim 21db18edd2097d438e083942771ff9568c63e57131e95f1fd13a40e27de0af53 /var/run/docker/libcontainerd/21db18edd2097d438e083942771ff9568c63e57131e95f1fd13a40e27de0af53...
           ├─11566 docker-containerd-shim 48ca7fef45698e7308173fa1bf77d26c8b0a177a959f5b1458527571e296334c /var/run/docker/libcontainerd/48ca7fef45698e7308173fa1bf77d26c8b0a177a959f5b1458527571e296334c...
           └─16991 docker-containerd-shim 988ef616ae028c4736783b934c1952b7e2c04278c8a1795c432dc96a8b9f5b87 /var/run/docker/libcontainerd/988ef616ae028c4736783b934c1952b7e2c04278c8a1795c432dc96a8b9f5b87...

aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal systemd[1]: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal systemd[1]: Unit docker.service entered failed state.
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal systemd[1]: docker.service failed.
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal systemd[1]: docker.service holdoff time over, scheduling restart.
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal systemd[1]: start request repeated too quickly for docker.service
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal systemd[1]: Unit docker.service entered failed state.
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal systemd[1]: docker.service failed.
```

```
# journalctl -xe
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal kernel: br-mailcow: port 16(vethd1d121b) entered forwarding state
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: panic: runtime error: invalid memory address or nil pointer dereference
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe1d5e8]
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: goroutine 205 [running]:
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: github.com/docker/docker/vendor/github.com/docker/libnetwork.(*endpoint).addServiceInfoToCluster(0xc4201f9a20, 0xc4202fad20,
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: /builddir/build/BUILD/docker-ce-17.06.2-ce/components/engine/_build/src/github.com/docker/docker/vendor/github.com/docker/lib
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: github.com/docker/docker/vendor/github.com/docker/libnetwork.(*sandbox).EnableService(0xc4202fad20, 0xc42042d440, 0x2658000)
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: /builddir/build/BUILD/docker-ce-17.06.2-ce/components/engine/_build/src/github.com/docker/docker/vendor/github.com/docker/lib
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: github.com/docker/docker/daemon.(*Daemon).ActivateContainerServiceBinding(0xc420077b00, 0xc4201ef200, 0x2f, 0x0, 0x0)
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: /builddir/build/BUILD/docker-ce-17.06.2-ce/components/engine/_build/src/github.com/docker/docker/daemon/container_operations.
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: github.com/docker/docker/daemon.(*Daemon).connectToNetwork(0xc420077b00, 0xc42042d440, 0xc4201ef110, 0x21, 0xc4200be480, 0x0,
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: /builddir/build/BUILD/docker-ce-17.06.2-ce/components/engine/_build/src/github.com/docker/docker/daemon/container_operations.
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: github.com/docker/docker/daemon.(*Daemon).allocateNetwork(0xc420077b00, 0xc42042d440, 0x0, 0x0)
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: /builddir/build/BUILD/docker-ce-17.06.2-ce/components/engine/_build/src/github.com/docker/docker/daemon/container_operations.
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: github.com/docker/docker/daemon.(*Daemon).initializeNetworking(0xc420077b00, 0xc42042d440, 0x0, 0x0)
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: /builddir/build/BUILD/docker-ce-17.06.2-ce/components/engine/_build/src/github.com/docker/docker/daemon/container_operations.
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: github.com/docker/docker/daemon.(*Daemon).containerStart(0xc420077b00, 0xc42042d440, 0x0, 0x0, 0x0, 0x0, 0x13eff01, 0x0, 0x0)
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: /builddir/build/BUILD/docker-ce-17.06.2-ce/components/engine/_build/src/github.com/docker/docker/daemon/start.go:140 +0x1f9
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: github.com/docker/docker/daemon.(*Daemon).restore.func2(0xc420ba82b0, 0xc420077b00, 0xc420013410, 0xc42042d440, 0xc4204b03c0)
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: /builddir/build/BUILD/docker-ce-17.06.2-ce/components/engine/_build/src/github.com/docker/docker/daemon/daemon.go:324 +0x24d
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: created by github.com/docker/docker/daemon.(*Daemon).restore
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal dockerd[16424]: /builddir/build/BUILD/docker-ce-17.06.2-ce/components/engine/_build/src/github.com/docker/docker/daemon/daemon.go:328 +0xa74
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal systemd[1]: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is failed.
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal systemd[1]: Unit docker.service entered failed state.
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal systemd[1]: docker.service failed.
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal systemd[1]: docker.service holdoff time over, scheduling restart.
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal systemd[1]: start request repeated too quickly for docker.service
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is failed.
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal systemd[1]: Unit docker.service entered failed state.
aug 19 16:53:14 ip-172-31-14-100.eu-central-1.compute.internal systemd[1]: docker.service failed.
aug 19 16:53:15 ip-172-31-14-100.eu-central-1.compute.internal firewalld[3391]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C POSTROUTING -p tcp -s 172.22.1.3 -d 172.22.1.3 --dport 587 -j MAS
aug 19 16:53:15 ip-172-31-14-100.eu-central-1.compute.internal kernel: br-mailcow: port 16(vethd1d121b) entered disabled state
aug 19 16:54:31 ip-172-31-14-100.eu-central-1.compute.internal dhclient[4042]: XMT: Solicit on eth0, interval 111940ms.
aug 19 16:56:23 ip-172-31-14-100.eu-central-1.compute.internal dhclient[4042]: XMT: Solicit on eth0, interval 117860ms.
```

Docker version looks like pretty outdated? 

```
# docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:        Tue Nov 14 22:03:51 2017
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by andryyy** [comment]
I see a Docker problem, not a mailcow problem. 

Docker is not starting.

**Comment by Lucky88888** [comment]
It is/was indeed a docker problem. I set up a new server and migrated everything. Now it works like a charm again.
