### ISSUE TITLE
Documentation - Amazon Linux 2 - Default MTU is 9001

### ISSUE THREAD

**Issue by christoph-kluge** [mailcow/mailcow-dockerized#2943]
Hello everybody, I'm new to mailcow. I'm migrating my existing mailserver aways from ISPConfig to mailcow. 

I just want to share my knowledge/error-path because I found no issues/documentation norr documentation for my issue. Gladly I found enough other issues about a non-matching MTU which finally lead me to the solution.

I have received the following error. 

```
acme-mailcow_1       | Mon Sep 16 20:22:10 UTC 2019 - Waiting for Docker API...OK
acme-mailcow_1       | Mon Sep 16 20:22:10 UTC 2019 - Waiting for database... Uptime: 3  Threads: 11  Questions: 43  Slow queries: 0  Opens: 36  Flush tables: 1  Open tables: 28  Queries per second avg: 14.333
acme-mailcow_1       | OK
acme-mailcow_1       | Mon Sep 16 20:22:10 UTC 2019 - Waiting for Nginx... OK
acme-mailcow_1       | Mon Sep 16 20:22:10 UTC 2019 - Waiting for domain table... OK
acme-mailcow_1       | Mon Sep 16 20:22:10 UTC 2019 - Initializing, please wait... 
acme-mailcow_1       | Mon Sep 16 20:22:10 UTC 2019 - Using existing domain key /var/lib/acme/acme/key.pem
acme-mailcow_1       | Mon Sep 16 20:22:10 UTC 2019 - Using existing Lets Encrypt account key /var/lib/acme/acme/account.pem
acme-mailcow_1       | Mon Sep 16 20:22:10 UTC 2019 - Detecting IP addresses... OK
acme-mailcow_1       | Mon Sep 16 20:23:12 UTC 2019 - Found A record for *
acme-mailcow_1       | Mon Sep 16 20:23:12 UTC 2019 - Confirmed A record *
acme-mailcow_1       | Mon Sep 16 20:23:12 UTC 2019 - Found A record for *
acme-mailcow_1       | Mon Sep 16 20:23:12 UTC 2019 - Confirmed A record *
acme-mailcow_1       | Mon Sep 16 20:23:13 UTC 2019 - Found new SAN *
acme-mailcow_1       | Mon Sep 16 20:23:13 UTC 2019 - Creating backups in /var/lib/acme/backups/2019-09-16_20_23_13/ ...
acme-mailcow_1       | Parsing account key...
acme-mailcow_1       | Parsing CSR...
acme-mailcow_1       | Found domains: *
acme-mailcow_1       | Getting directory...
acme-mailcow_1       | Traceback (most recent call last):
acme-mailcow_1       |   File "/usr/bin/acme-tiny", line 10, in <module>
acme-mailcow_1       |     sys.exit(main())
acme-mailcow_1       |   File "/usr/lib/python3.7/site-packages/acme_tiny.py", line 194, in main
acme-mailcow_1       |     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
acme-mailcow_1       |   File "/usr/lib/python3.7/site-packages/acme_tiny.py", line 106, in get_crt
acme-mailcow_1       |     directory, _, _ = _do_request(directory_url, err_msg="Error getting directory")
acme-mailcow_1       |   File "/usr/lib/python3.7/site-packages/acme_tiny.py", line 46, in _do_request
acme-mailcow_1       |     raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
acme-mailcow_1       | ValueError: Error getting directory:
acme-mailcow_1       | Url: https://acme-v02.api.letsencrypt.org/directory
acme-mailcow_1       | Data: None
acme-mailcow_1       | Response Code: None
acme-mailcow_1       | Response: <urlopen error [Errno -3] Try again>
```

Per default Amazon Linux 2 has enabled jumboframes. This lead acme to fail with `<urlopen error [Errno -3] Try again>`. As soon as I have changed the MTU to 1500 everything was fine. 

`sudo ip link set dev eth0 mtu 1500`

I took this from the [AWS Documentation](docs.aws.amazon.com/en_pv/AWSEC2/latest/UserGuide/network_mtu.html#set_mtu).

**For all others simply copy/pasting this:** don't forget to adopt the required changes in order to persist the new MTU after a reboot.

**Comment by andryyy** [comment]
Hi,
That's a useful information, thanks. It looks like it supports 9001, but does not have it enabled by default.

**Comment by christoph-kluge** [comment]
If necessary I can also do some tests for your and document all those things later. Since I'm in a research mode I'm fine to restart the whole procedure because I'm automating it. I may also adopt the documentation especially for an AWS setup on Amazon Linux 2. 

Let me know, I'm happy to contribute 👍

**Comment by MAGICCC** [comment]
A PR on the docs repo would be nice then
