### ISSUE TITLE
Upgraded and mysql error (gateway 502)

### ISSUE THREAD

**Issue by kilo42L** [mailcow/mailcow-dockerized#2959]
Hello, I upgraded mailcow and everything starts up but webgui hangs and eventually works and I get a mysql error.

```
MySQL error: PDOException: SQLSTATE[HY000]: General error: 1577 Cannot proceed, because event scheduler is disabled in /web/inc/init_db.inc.php:989 Stack trace: #0 /web/inc/init_db.inc.php(989): PDO->exec('DROP EVENT IF E...') #1 /web/inc/prerequisites.inc.php(184): init_db_schema() #2 /web/admin.php(2): require_once('/web/inc/prereq...') #3 {main}

MySQL error: PDOException: SQLSTATE[HY000]: General error: 1577 Cannot proceed, because event scheduler is disabled in /web/inc/init_db.inc.php:989 Stack trace: #0 /web/inc/init_db.inc.php(989): PDO->exec('DROP EVENT IF E...') #1 /web/inc/prerequisites.inc.php(184): init_db_schema() #2 /web/index.php(2): require_once('/web/inc/prereq...') #3 {main}

MySQL error: PDOException: SQLSTATE[HY000]: General error: 1005 Can't create table `mailcow`.`sieve_filters` (errno: 121 "Duplicate key on write or update") in /web/inc/init_db.inc.php:881 Stack trace: #0 /web/inc/init_db.inc.php(881): PDO->query('ALTER TABLE `si...') #1 /web/inc/prerequisites.inc.php(184): init_db_schema() #2 /web/json_api.php(16): require_once('/web/inc/prereq...') #3 {main}
```
Then I ran this command:
docker-compose logs mysql-mailcow

```
mysql-mailcow_1      | 2019-09-20 19:40:19 0 [Note] mysqld (mysqld 10.3.18-MariaDB-1:10.3.18+maria~bionic) starting as process 1 ...
mysql-mailcow_1      | 2019-09-20 19:40:19 0 [Note] InnoDB: Using Linux native AIO
mysql-mailcow_1      | 2019-09-20 19:40:19 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql-mailcow_1      | 2019-09-20 19:40:19 0 [Note] InnoDB: Uses event mutexes
mysql-mailcow_1      | 2019-09-20 19:40:19 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql-mailcow_1      | 2019-09-20 19:40:19 0 [Note] InnoDB: Number of pools: 1
mysql-mailcow_1      | 2019-09-20 19:40:19 0 [Note] InnoDB: Using generic crc32 instructions
mysql-mailcow_1      | 2019-09-20 19:40:19 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
mysql-mailcow_1      | 2019-09-20 19:40:19 0 [Note] InnoDB: Completed initialization of buffer pool
mysql-mailcow_1      | 2019-09-20 19:40:19 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql-mailcow_1      | 2019-09-20 19:40:19 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mysql-mailcow_1      | 2019-09-20 19:40:19 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql-mailcow_1      | 2019-09-20 19:40:19 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql-mailcow_1      | 2019-09-20 19:40:19 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql-mailcow_1      | 2019-09-20 19:40:19 0 [Note] InnoDB: 10.3.18 started; log sequence number 46478519; transaction id 146490
mysql-mailcow_1      | 2019-09-20 19:40:19 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql-mailcow_1      | 2019-09-20 19:40:20 0 [Note] Server socket created on IP: '::'.
mysql-mailcow_1      | 2019-09-20 19:40:20 0 [Warning] 'proxies_priv' entry '@% root@7991368bfcf3' ignored in --skip-name-resolve mode.
mysql-mailcow_1      | 2019-09-20 19:40:20 0 [ERROR] Incorrect definition of table mysql.event: expected column 'sql_mode' at position 14 to have type set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','IGNORE_BAD_TABLE_OPTIONS','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_ALL_TABLES','NO_ZERO_IN_DATE','NO_ZERO_DATE','INVALID_DATES','ERROR_FOR_DIVISION_BY_ZERO','TRADITIONAL','NO_AUTO_CREATE_USER','HIGH_NOT_PRECEDENCE','NO_ENGINE_SUBSTITUTION','PAD_CHAR_TO_FULL_LENGTH','EMPTY_STRING_IS_NULL','SIMULTANEOUS_ASSIGNMENT'), found type set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','IGNORE_BAD_TABLE_OPTIONS','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_VALU
mysql-mailcow_1      | 2019-09-20 19:40:20 0 [ERROR] mysqld: Event Scheduler: An error occurred when initializing system tables. Disabling the Event Scheduler.
mysql-mailcow_1      | 2019-09-20 19:40:20 0 [Note] mysqld: ready for connections.
mysql-mailcow_1      | Version: '10.3.18-MariaDB-1:10.3.18+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
mysql-mailcow_1      | 2019-09-20 19:40:20 0 [Note] InnoDB: Buffer pool(s) load completed at 190920 19:40:20

```

Can someone help me with this?
Thank you.

**Comment by andryyy** [comment]
It WILL print errors at first in the MySQL log, because it needs to apply an upgrade after starting SQL. 

After it applied an upgrade, it will run fine. 

If you restarted containers in the middle of the update progress, you end up with broken tables.

Steps: Backup SQL, run upgrade and WAIT. It will show errors in msql-mailcow, because it starts SQL with an old data dir and THEN applies an upgrade and restarts the stack.

**Comment by kilo42L** [comment]
Thanks Andre, I let it run all night and this morning it is very slow and showing this:


-MySQL error: PDOException: SQLSTATE[HY000]: General error: 1577 Cannot proceed, because event scheduler is disabled in /web/inc/init_db.inc.php:989 Stack trace: #0 /web/inc/init_db.inc.php(989): PDO->exec('DROP EVENT IF E...') #1 /web/inc/prerequisites.inc.php(184): init_db_schema() #2 /web/index.php(2): require_once('/web/inc/prereq...') #3 {main}

Everything seems to work intermittently. Send like MySQL is restarting though.

**Comment by kilo42L** [comment]
The only thing I have changed from the default installation is added rainloop with seive

**Comment by andryyy** [comment]
I cannot help you. Revert to a backup and try again, please. "php-fpm-mailcow" logs would be helpful.

**Comment by kilo42L** [comment]
Ok, I rolled back my installation and upgraded my debian installation first then I did a 'Manual Mailcow' update and everything is perfect.
Before I auto updated mailcow and had errors.

-Closed
Thanks again for your help Andry
