### ISSUE TITLE
Cannot proceed, because event scheduler is disabled after backup restore

### ISSUE THREAD

**Issue by Wqrld** [mailcow/mailcow-dockerized#3123]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x ] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: I'm getting Cannot proceed, because event scheduler is disabled in /web/inc/init_db.inc.php:1072 errors in the UI after restoring a backup made with the helper script to a new machine (which had a blank install of mailcow)

My issue is...
create a backup with the helper script
reinstall mailcow on the new machine
import the backup with option all
import the backup with option mysql (because all doesnt add that for some reason)

__I have tried or I do...__ 
- [x ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**
Ubuntu 18.04
running in Virtualizor
newest docker/docker compose
nginx as reverse proxy

Further information (where applicable):

The default logins stay but the domain does get imported. These errors show up in a red box on every page though (sometimes multiple per page).

MySQL-fout: PDOException: SQLSTATE[HY000]: General error: 1577 Cannot proceed, because event scheduler is disabled in /web/inc/init_db.inc.php:1072 Stack trace: #0 /web/inc/init_db.inc.php(1072): PDO->exec('DROP EVENT IF E...') #1 /web/inc/prerequisites.inc.php(218): init_db_schema() #2 /web/json_api.php(16): require_once('/web/inc/prereq...') #3 {main}

MySQL-fout: PDOException: SQLSTATE[HY000]: General error: 1005 Can't create table `mailcow`.`user_acl` (errno: 121 "Duplicate key on write or update") in /web/inc/init_db.inc.php:953 Stack trace: #0 /web/inc/init_db.inc.php(953): PDO->query('ALTER TABLE `us...') #1 /web/inc/prerequisites.inc.php(218): init_db_schema() #2 /web/mailbox.php(2): require_once('/web/inc/prereq...') #3 {main}

**Comment by Wqrld** [comment]
root@Node1:~/music/avaire# docker exec $(docker ps -qf name=dovecot-mailcow) doveadm force-resync -A '*'
Error: auth-master: userdb list: connect(/var/run/dovecot/auth-userdb) failed: No such file or directory
Panic: file auth-master.c: line 439 (auth_master_unset_io): assertion failed: (conn->to == NULL)
Error: Raw backtrace: /usr/lib/dovecot/libdovecot.so.0(+0xeebcb) [0x7fce0667dbcb] -> /usr/lib/dovecot/libdovecot.so.0(+0xeec01) [0x7fce0667dc01] -> /usr/lib/dovecot/libdovecot.so.0(+0x4e555) [0x7fce065dd555] -> /usr/lib/dovecot/libdovecot.so.0(+0x4c111) [0x7fce065db111] -> /usr/lib/dovecot/libdovecot.so.0(+0xdb4e9) [0x7fce0666a4e9] -> /usr/lib/dovecot/libdovecot.so.0(auth_master_user_list_deinit+0xe5) [0x7fce0666c075] -> /usr/lib/dovecot/libdovecot-storage.so.0(mail_storage_service_all_next+0x52) [0x7fce0679d5b2] -> /usr/bin/doveadm(+0x319a2) [0x559074a549a2] -> /usr/bin/doveadm(doveadm_cmd_ver2_to_mail_cmd_wrapper+0x21a) [0x559074a5563a] -> /usr/bin/doveadm(doveadm_cmd_run_ver2+0x4e5) [0x559074a65e15] -> /usr/bin/doveadm(doveadm_cmd_try_run_ver2+0x37) [0x559074a65e67] -> /usr/bin/doveadm(main+0x1d1) [0x559074a44b91] -> /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fce0621609b] -> /usr/bin/doveadm(_start+0x2a) [0x559074a4502a]

Resyncing gives a error

**Comment by Wqrld** [comment]
closing this for https://github.com/mailcow/mailcow-dockerized/issues/3115
It seems to be almost the same issue
