### ISSUE TITLE
[ACME] [Documentation] Cert renew fails with additional SAN domains.

### ISSUE THREAD

**Issue by zege-at** [mailcow/mailcow-dockerized#3252]
Please **try** to answer all questions. If you cannot, don't just delete it. If you completely ignore or remove the whole template, your issue is either closed or ignored, too. :( This is (not only) because we are evil. Many awesome mailcow supporters don't bother to reply to an issue, when crucial information is missing. Especially when it could have been answered by using this issue template. We need as much information as possible. Please post all logs, do not copy that one line you think may be interesting. Copy the whole bunch and remove sensible information. :) Thank you!

**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

ACME Container fails to verify Domains that are in ADDITIONAL_SAN section of config, when a reverse proxy (nginx) is used.

**Problem can be solved when adding the ADDITIONAL_SAN Domains to the Reverse Proxy.
Maybe Documentation needs update.**

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. Set up Nginx reverse Proxy exactly like in the documentation.
2. Add ADDITIONAL_SAN domains
3. Restart ACME container

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

```
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Attaching to mailcowdockerized_acme-mailcow_1
acme-mailcow_1       | Mon Jan  6 10:36:45 CET 2020 - Waiting for Docker API...OK
acme-mailcow_1       | Mon Jan  6 10:36:45 CET 2020 - Waiting for database... Uptime: 63246  Threads: 20  Questions: 201266  Slow queries: 1  Opens: 246  Flush tables: 1  Open tables: 238  Queries per second avg: 3.182
acme-mailcow_1       | OK
acme-mailcow_1       | Mon Jan  6 10:36:45 CET 2020 - Waiting for Nginx... OK
acme-mailcow_1       | Mon Jan  6 10:36:45 CET 2020 - Waiting for domain table... OK
acme-mailcow_1       | Mon Jan  6 10:36:45 CET 2020 - Initializing, please wait... 
acme-mailcow_1       | Mon Jan  6 10:36:45 CET 2020 - Using existing domain rsa key /var/lib/acme/acme/key.pem
acme-mailcow_1       | Mon Jan  6 10:36:45 CET 2020 - Using existing Lets Encrypt account key /var/lib/acme/acme/account.pem
acme-mailcow_1       | Mon Jan  6 10:36:45 CET 2020 - Detecting IP addresses... OK
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Validated CAA for parent domain zegenet.eu
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for mail.crazypistons.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for imap.crazypistons.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for pop.crazypistons.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for smtp.crazypistons.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for autodiscover.crazypistons.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for autodiscover.crazypistons.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for autoconfig.crazypistons.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for mail.sportshooters.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for imap.sportshooters.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for pop.sportshooters.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for smtp.sportshooters.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for autodiscover.sportshooters.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for autodiscover.sportshooters.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for autoconfig.sportshooters.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for mail.zege.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for imap.zege.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for pop.zege.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for smtp.zege.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for autodiscover.zege.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for autodiscover.zege.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for autoconfig.zege.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for mail.zege.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for imap.zege.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for pop.zege.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for smtp.zege.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Found A record for autodiscover.zege.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:46 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Found A record for autodiscover.zege.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Found A record for autoconfig.zege.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Found A record for mail.zegenet.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Found A record for imap.zegenet.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Found A record for pop.zegenet.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Found A record for smtp.zegenet.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Found A record for autodiscover.zegenet.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Found A record for autodiscover.zegenet.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - No A or AAAA record found for hostname autoconfig.zegenet.eu
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Found A record for mail.zehetner.or.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Found A record for imap.zehetner.or.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Found A record for pop.zehetner.or.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Found A record for smtp.zehetner.or.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Found A record for autodiscover.zehetner.or.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Found A record for autodiscover.zehetner.or.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Found A record for autoconfig.zehetner.or.at: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Found A record for hal9000.zegenet.eu: 176.9.102.232
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Confirmed A record 176.9.102.232
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Certificate /var/lib/acme/hal9000.zegenet.eu/cert.pem missing or changed domains 'hal9000.zegenet.eu autoconfig.crazypistons.at autoconfig.sportshooters.eu autoconfig.zege.at autoconfig.zege.eu autoconfig.zehetner.or.at autodiscover.crazypistons.at autodiscover.sportshooters.eu autodiscover.zege.at autodiscover.zege.eu autodiscover.zegenet.eu autodiscover.zehetner.or.at imap.crazypistons.at imap.sportshooters.eu imap.zege.at imap.zege.eu imap.zegenet.eu imap.zehetner.or.at mail.crazypistons.at mail.sportshooters.eu mail.zege.at mail.zege.eu mail.zegenet.eu mail.zehetner.or.at pop.crazypistons.at pop.sportshooters.eu pop.zege.at pop.zege.eu pop.zegenet.eu pop.zehetner.or.at smtp.crazypistons.at smtp.sportshooters.eu smtp.zege.at smtp.zege.eu smtp.zegenet.eu smtp.zehetner.or.at' - start obtaining
acme-mailcow_1       | Mon Jan  6 10:36:47 CET 2020 - Creating backups in /var/lib/acme/backups/hal9000.zegenet.eu/2020-01-06_10_36_47 ...
acme-mailcow_1       | Parsing account key...
acme-mailcow_1       | Parsing CSR...
acme-mailcow_1       | Found domains: smtp.crazypistons.at, pop.crazypistons.at, mail.zege.eu, autoconfig.sportshooters.eu, autodiscover.zegenet.eu, autodiscover.zehetner.or.at, pop.zege.eu, pop.zegenet.eu, mail.zehetner.or.at, pop.sportshooters.eu, smtp.zege.at, pop.zehetner.or.at, autodiscover.zege.at, mail.crazypistons.at, autoconfig.zege.eu, pop.zege.at, autodiscover.sportshooters.eu, smtp.zehetner.or.at, imap.zege.at, imap.zehetner.or.at, hal9000.zegenet.eu, imap.crazypistons.at, autoconfig.zege.at, autodiscover.zege.eu, mail.sportshooters.eu, imap.zege.eu, mail.zegenet.eu, imap.zegenet.eu, smtp.zegenet.eu, autoconfig.zehetner.or.at, autodiscover.crazypistons.at, mail.zege.at, autoconfig.crazypistons.at, smtp.sportshooters.eu, smtp.zege.eu, imap.sportshooters.eu
acme-mailcow_1       | Getting directory...
acme-mailcow_1       | Directory found!
acme-mailcow_1       | Registering account...
acme-mailcow_1       | Already registered!
acme-mailcow_1       | Creating new order...
acme-mailcow_1       | Order created!
acme-mailcow_1       | Verifying autoconfig.crazypistons.at...
acme-mailcow_1       | autoconfig.crazypistons.at verified!
acme-mailcow_1       | Verifying autoconfig.sportshooters.eu...
acme-mailcow_1       | autoconfig.sportshooters.eu verified!
acme-mailcow_1       | Verifying autoconfig.zege.at...
acme-mailcow_1       | autoconfig.zege.at verified!
acme-mailcow_1       | Verifying autoconfig.zege.eu...
acme-mailcow_1       | autoconfig.zege.eu verified!
acme-mailcow_1       | Verifying autoconfig.zehetner.or.at...
acme-mailcow_1       | autoconfig.zehetner.or.at verified!
acme-mailcow_1       | Verifying autodiscover.crazypistons.at...
acme-mailcow_1       | autodiscover.crazypistons.at verified!
acme-mailcow_1       | Verifying autodiscover.sportshooters.eu...
acme-mailcow_1       | autodiscover.sportshooters.eu verified!
acme-mailcow_1       | Verifying autodiscover.zege.at...
acme-mailcow_1       | autodiscover.zege.at verified!
acme-mailcow_1       | Verifying autodiscover.zege.eu...
acme-mailcow_1       | autodiscover.zege.eu verified!
acme-mailcow_1       | Verifying autodiscover.zegenet.eu...
acme-mailcow_1       | autodiscover.zegenet.eu verified!
acme-mailcow_1       | Verifying autodiscover.zehetner.or.at...
acme-mailcow_1       | autodiscover.zehetner.or.at verified!
acme-mailcow_1       | Verifying hal9000.zegenet.eu...
acme-mailcow_1       | hal9000.zegenet.eu verified!
acme-mailcow_1       | Verifying imap.crazypistons.at...
acme-mailcow_1       | Traceback (most recent call last):
acme-mailcow_1       |   File "/usr/bin/acme-tiny", line 8, in <module>
acme-mailcow_1       |     sys.exit(main())
acme-mailcow_1       |   File "/usr/lib/python3.7/site-packages/acme_tiny.py", line 194, in main
acme-mailcow_1       |     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
acme-mailcow_1       |   File "/usr/lib/python3.7/site-packages/acme_tiny.py", line 149, in get_crt
acme-mailcow_1       |     raise ValueError("Challenge did not pass for {0}: {1}".format(domain, authorization))
acme-mailcow_1       | ValueError: Challenge did not pass for imap.crazypistons.at: {'identifier': {'type': 'dns', 'value': 'imap.crazypistons.at'}, 'status': 'invalid', 'expires': '2020-01-13T09:30:26Z', 'challenges': [{'type': 'http-01', 'status': 'invalid', 'error': {'type': 'urn:ietf:params:acme:error:unauthorized', 'detail': 'Invalid response from https://imap.crazypistons.at/.well-known/acme-challenge/dNjkJXyBFDT8FenD7SBb3Ml6BgBdYtyiG4JmfF_NRuY [176.9.102.232]: 404', 'status': 403}, 'url': 'https://acme-v02.api.letsencrypt.org/acme/chall-v3/2136609181/CGHu_Q', 'token': 'dNjkJXyBFDT8FenD7SBb3Ml6BgBdYtyiG4JmfF_NRuY', 'validationRecord': [{'url': 'http://imap.crazypistons.at/.well-known/acme-challenge/dNjkJXyBFDT8FenD7SBb3Ml6BgBdYtyiG4JmfF_NRuY', 'hostname': 'imap.crazypistons.at', 'port': '80', 'addressesResolved': ['176.9.102.232'], 'addressUsed': '176.9.102.232'}, {'url': 'https://imap.crazypistons.at/.well-known/acme-challenge/dNjkJXyBFDT8FenD7SBb3Ml6BgBdYtyiG4JmfF_NRuY', 'hostname': 'imap.crazypistons.at', 'port': '443', 'addressesResolved': ['176.9.102.232'], 'addressUsed': '176.9.102.232'}]}]}
acme-mailcow_1       | Mon Jan  6 10:37:44 CET 2020 - Failed to obtain certificate /var/lib/acme/hal9000.zegenet.eu/cert.pem for domains 'hal9000.zegenet.eu autoconfig.crazypistons.at autoconfig.sportshooters.eu autoconfig.zege.at autoconfig.zege.eu autoconfig.zehetner.or.at autodiscover.crazypistons.at autodiscover.sportshooters.eu autodiscover.zege.at autodiscover.zege.eu autodiscover.zegenet.eu autodiscover.zehetner.or.at imap.crazypistons.at imap.sportshooters.eu imap.zege.at imap.zege.eu imap.zegenet.eu imap.zehetner.or.at mail.crazypistons.at mail.sportshooters.eu mail.zege.at mail.zege.eu mail.zegenet.eu mail.zehetner.or.at pop.crazypistons.at pop.sportshooters.eu pop.zege.at pop.zege.eu pop.zegenet.eu pop.zehetner.or.at smtp.crazypistons.at smtp.sportshooters.eu smtp.zege.at smtp.zege.eu smtp.zegenet.eu smtp.zehetner.or.at'
acme-mailcow_1       | OK
acme-mailcow_1       | Mon Jan  6 10:37:44 CET 2020 - Some errors occurred, retrying in 30 minutes...
acme-mailcow_1       | OK
```

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 |
| Is Apparmor, SELinux or similar active? | Apparmor |
| Virtualization technlogy (KVM, VMware, Xen, etc) | None |
| Server/VM specifications (Memory, CPU Cores) | 16GB, Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz  |
| Docker Version (`docker version`) | 19.03.5 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1 |
| Reverse proxy (custom solution) | Nginx |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

**Comment by andryyy** [comment]
Not a mailcow bug, you need to make sure the domain name can actually be validated. We cannot fix that for you. :) You need to configure the reverse proxy accordingly (the documentation does not tell you how to setup other aliases, it is not a tutorial for "how to setup an Nginx RP"). It works as-is for MAILCOW_HOSTNAME and auto* domains.

The RP does probably not pass the required name to mailcow.

André

**Comment by zege-at** [comment]
As official documentation does provide a reverse proxy config and shows how to add ADDITIONAL_SANs I think it would be nice to have a note in the ADDITIONAL_SAN section that tells you to be careful when using a reverse proxy.
Would have saved me a lot of time searching for the problem, as ACME failed with different domains each time.
