### ISSUE TITLE
Possible regression in acme-mailcow 1.80

### ISSUE THREAD

**Issue by g4rf** [mailcow/mailcow-dockerized#4392]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
Just testing with the newest mailcow-dockerized version from the repo. After `docker-compose up -d` the containers running, but `acme-mailcow` has an error obtaining the certificates:

```
cat: can’t open ‘/etc/ssl/openssl.cnf’: No such file or directory
acme-mailcow_1 | unable to find ‘distinguished_name’ in config
acme-mailcow_1 | problems making Certificate Request
...
```

If I change the `acme-mailcow` version in the `docker-compose.yml` to **1.79** the error is gone and the certificates are obtained.

## Logs
```
Attaching to piratemail_acme-mailcow_1
acme-mailcow_1       | Sat Dec 18 15:56:31 CET 2021 - Waiting for Docker API...
acme-mailcow_1       | Sat Dec 18 15:56:31 CET 2021 - Docker API OK
acme-mailcow_1       | Sat Dec 18 15:56:31 CET 2021 - Waiting for Postfix...
acme-mailcow_1       | Sat Dec 18 15:56:31 CET 2021 - Postfix OK
acme-mailcow_1       | Sat Dec 18 15:56:31 CET 2021 - Waiting for Dovecot...
acme-mailcow_1       | Sat Dec 18 15:56:31 CET 2021 - Dovecot OK
acme-mailcow_1       | Sat Dec 18 15:56:31 CET 2021 - Waiting for database...
acme-mailcow_1       | Sat Dec 18 15:56:32 CET 2021 - Database OK
acme-mailcow_1       | Sat Dec 18 15:56:32 CET 2021 - Waiting for Nginx...
acme-mailcow_1       | Sat Dec 18 15:56:40 CET 2021 - Nginx OK
acme-mailcow_1       | Sat Dec 18 15:56:40 CET 2021 - Waiting for resolver...
acme-mailcow_1       | Sat Dec 18 15:56:40 CET 2021 - Resolver OK
acme-mailcow_1       | Sat Dec 18 15:56:40 CET 2021 - Waiting for domain table...
acme-mailcow_1       | OK
acme-mailcow_1       | Sat Dec 18 15:56:41 CET 2021 - Initializing, please wait...
acme-mailcow_1       | unable to load certificate
acme-mailcow_1       | 139686046726984:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
acme-mailcow_1       | unable to load certificate
acme-mailcow_1       | 139752372075336:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
acme-mailcow_1       | Sat Dec 18 15:56:41 CET 2021 - Using existing domain rsa key /var/lib/acme/acme/key.pem
acme-mailcow_1       | Sat Dec 18 15:56:41 CET 2021 - Using existing Lets Encrypt account key /var/lib/acme/acme/account.pem
acme-mailcow_1       | Sat Dec 18 15:56:41 CET 2021 - Detecting IP addresses...
acme-mailcow_1       | Sat Dec 18 15:56:41 CET 2021 - OK: 1.2.3.4, dead::beef
acme-mailcow_1       | Sat Dec 18 15:56:42 CET 2021 - Found AAAA record for my.domain.de: dead::beef - skipping A record check
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Sat Dec 18 15:56:42 CET 2021 - Confirmed AAAA record with IP dead:beef
acme-mailcow_1       | Sat Dec 18 15:56:42 CET 2021 - Certificate /var/lib/acme/my.domainde/cert.pem missing or changed domains 'my.domain.de' - start obtaining
acme-mailcow_1       | cat: can't open '/etc/ssl/openssl.cnf': No such file or directory
acme-mailcow_1       | unable to find 'distinguished_name' in config
acme-mailcow_1       | problems making Certificate Request
acme-mailcow_1       | 140678094932808:error:0E06D06C:configuration file routines:NCONF_get_string:no value:crypto/conf/conf_lib.c:273:group=req name=distinguished_name
acme-mailcow_1       | Sat Dec 18 15:56:42 CET 2021 - Checking resolver...
acme-mailcow_1       | Sat Dec 18 15:56:42 CET 2021 - Resolver OK
acme-mailcow_1       | Sat Dec 18 15:56:42 CET 2021 - Using command acme-tiny   --account-key /var/lib/acme/acme/account.pem --disable-check --csr /var/lib/acme/my.domain.de/acme.csr --acme-dir /var/www/acme/
acme-mailcow_1       | Parsing account key...
acme-mailcow_1       | Parsing CSR...
acme-mailcow_1       | Traceback (most recent call last):
acme-mailcow_1       |   File "/usr/bin/acme-tiny", line 8, in <module>
acme-mailcow_1       |     sys.exit(main())
acme-mailcow_1       |   File "/usr/lib/python3.9/site-packages/acme_tiny.py", line 195, in main
acme-mailcow_1       |     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact, check_port=args.check_port)
acme-mailcow_1       |   File "/usr/lib/python3.9/site-packages/acme_tiny.py", line 90, in get_crt
acme-mailcow_1       |     out = _cmd(["openssl", "req", "-in", csr, "-noout", "-text"], err_msg="Error loading {0}".format(csr))
acme-mailcow_1       |   File "/usr/lib/python3.9/site-packages/acme_tiny.py", line 28, in _cmd
acme-mailcow_1       |     raise IOError("{0}\n{1}".format(err_msg, err))
acme-mailcow_1       | OSError: Error loading /var/lib/acme/my.domain.de/acme.csr
acme-mailcow_1       | b'unable to load X509 request\n140383324310344:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: CERTIFICATE REQUEST\n'
acme-mailcow_1       | Sat Dec 18 15:56:44 CET 2021 - Failed to obtain certificate /var/lib/acme/my.domain.de/cert.pem for domains 'my.domain.de'
acme-mailcow_1       | OK
acme-mailcow_1       | Sat Dec 18 15:56:44 CET 2021 - Some errors occurred, retrying in 30 minutes...
acme-mailcow_1       | OK
```

## Reproduction
Just do `docker-compose up -d` and the error persists.

If I change the `acme-mailcow` version in the `docker-compose.yml` to **1.79** the error is gone.

## System information
| Question | Answer |
| --- | --- |
| My operating system | Debian Buster |
| Is Apparmor, SELinux or similar active? | No. |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | No |
| Server/VM specifications (Memory, CPU Cores) | 2GB + 6G Swap, 1 CPU (local staging environement) |
| Docker Version (`docker version`) | 20.10.12 |
| Docker-Compose Version (`docker-compose version`) | 1.29.2 |
| Reverse proxy (custom solution) | No |

**Comment by andryyy** [comment]
@DerLinkman

**Comment by maborak** [comment]
Both images are different in ssl structure.

1.79
```
$ sudo docker run -it mailcow/acme:1.79 ls -l /etc/ssl
total 48
lrwxrwxrwx    1 root     root            25 Aug 31 13:34 cert.pem -> certs/ca-certificates.crt
drwxr-xr-x    2 root     root         12288 Sep  1 13:39 certs
-rw-r--r--    1 root     root           412 Aug 24 16:17 ct_log_list.cnf
-rw-r--r--    1 root     root           412 Aug 24 16:17 ct_log_list.cnf.dist
drwxr-xr-x    2 root     root            45 Aug 31 13:34 misc
-rw-r--r--    1 root     root         10909 Aug 24 16:17 openssl.cnf
-rw-r--r--    1 root     root         10909 Aug 24 16:17 openssl.cnf.dist
drwxr-xr-x    2 root     root             6 Aug 31 13:34 private
```
1.80

```
$ sudo docker run -it mailcow/acme:1.80 ls -l /etc/ssl
total 16
lrwxrwxrwx    1 root     root            25 Nov 24 09:20 cert.pem -> certs/ca-certificates.crt
drwxr-xr-x    2 root     root         12288 Dec 17 11:51 certs
```

In the case of 1.80 the file is under `/etc/ssl1.1`
```
$ sudo docker run -it mailcow/acme:1.80 ls -l /etc/ssl1.1
total 28
lrwxrwxrwx    1 root     root            15 Nov 24 09:20 cert.pem -> ../ssl/cert.pem
lrwxrwxrwx    1 root     root            12 Nov 24 09:20 certs -> ../ssl/certs
lrwxrwxrwx    1 root     root            22 Nov 24 09:20 ct_log_list.cnf -> ../ssl/ct_log_list.cnf
-rw-r--r--    1 root     root           412 Nov 22 23:49 ct_log_list.cnf.dist
-rw-r--r--    1 root     root         10909 Nov 22 23:49 openssl.cnf
-rw-r--r--    1 root     root         10909 Nov 22 23:49 openssl.cnf.dist
drwxr-xr-x    2 root     root             6 Nov 24 09:20 private
```

**Comment by numero69** [comment]
Changing the version to 1.79 does not work either for me.

**Comment by MAGICCC** [comment]
Strange, when I rebuild the Dockerfile from master, I dont have the /etc/ssl1.1 folder

**Comment by abakisensoy** [comment]
> Changing the version to 1.79 does not work either for me.

It worked for me.

**Comment by MAGICCC** [comment]
HI I just rebuilt the image and pushed it again as 1.80. Can you try again?
You may need to do a `docker-compose pull; docker-compose up -d`

```
docker run -it mailcow/acme:1.80 ls -l /etc/ssl
Unable to find image 'mailcow/acme:1.80' locally
1.80: Pulling from mailcow/acme
97518928ae5f: Pull complete
affaae681583: Pull complete
0615b5094ccc: Pull complete
21cee4d6db90: Pull complete
d68e4ddc3397: Pull complete
fb2d6f28bf68: Pull complete
94d4c18a5c4d: Pull complete
d76536fd3fc8: Pull complete
Digest: sha256:4f002142d23c11d2d96f0fa3b5690bcb3bfd057020976e03ae4ca693deb6f671
Status: Downloaded newer image for mailcow/acme:1.80
total 60
lrwxrwxrwx    1 root     root            25 Nov 12 09:18 cert.pem -> certs/ca-certificates.crt
drwxr-xr-x    1 root     root         20480 Dec 20 17:12 certs
-rw-r--r--    1 root     root           412 Aug 24 15:52 ct_log_list.cnf
-rw-r--r--    1 root     root           412 Aug 24 15:52 ct_log_list.cnf.dist
drwxr-xr-x    2 root     root          4096 Nov 12 09:18 misc
-rw-r--r--    1 root     root         10909 Aug 24 15:52 openssl.cnf
-rw-r--r--    1 root     root         10909 Aug 24 15:52 openssl.cnf.dist
drwxr-xr-x    2 root     root          4096 Nov 12 09:18 private

```

**Comment by l-with** [comment]
I tried my deployment with the rebuilt image and it worked.
Thank you very much!

**Comment by MAGICCC** [comment]
No problem

Looks like its fine now

**Comment by DerLinkman** [comment]
I tried to change the obtain-certificate.sh Path in line 83 to the new /etc/ssl1.1 Path and it seem to work with Alpine 3.15. @MAGICCC 

If i didn´t change a different issue appears which cause a acme script abort.

**Comment by MAGICCC** [comment]
I doubt it will break anything else, I quick checked the script before my holiday and couldnt find some other lines which could be affected. I can check it over the weekend again

**Comment by DerLinkman** [comment]
Yeah i rebuild the image on a seperate new fresh machine, forced a SSL cert recreation with `touch data/assets/ssl/force_renew` but i get those errors:

```
acme-mailcow_1       | Traceback (most recent call last):
acme-mailcow_1       |   File "/usr/bin/acme-tiny", line 8, in <module>
acme-mailcow_1       |     sys.exit(main())
acme-mailcow_1       |   File "/usr/lib/python3.9/site-packages/acme_tiny.py", line 195, in main
acme-mailcow_1       |     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact, check_port=args.check_port)
acme-mailcow_1       |   File "/usr/lib/python3.9/site-packages/acme_tiny.py", line 90, in get_crt
acme-mailcow_1       |     out = _cmd(["openssl", "req", "-in", csr, "-noout", "-text"], err_msg="Error loading {0}".format(csr))
acme-mailcow_1       |   File "/usr/lib/python3.9/site-packages/acme_tiny.py", line 28, in _cmd
acme-mailcow_1       |     raise IOError("{0}\n{1}".format(err_msg, err))
acme-mailcow_1       | OSError: Error loading /var/lib/acme/mail01.schmeters.de/acme.csr
acme-mailcow_1       | b'unable to load X509 request\n139913126136648:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: CERTIFICATE REQUEST\n'
acme-mailcow_1       | Tue Jan 18 15:30:47 CET 2022 - Failed to obtain certificate /var/lib/acme/mail01.schmeters.de/cert.pem for domains 'mail01.schmeters.de'
```

As i want to merge the staging into master this Friday (aprox.) and you can´t take a look into the script until the weekend (due to holiday, which are well deserved) we can left out acme until this issue is fixed.

**Comment by DerLinkman** [comment]
Ok Problem solved thanks to @mkuron.

**Comment by WEBDIENSTE** [comment]
I got the same problem with acme 1.82.
