### ISSUE TITLE
netfilter restarts after update

### ISSUE THREAD

**Issue by bodsch** [mailcow/mailcow-dockerized#4474]
clea**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
After an update today, the netfilter container are permanently restarting.

## Logs

```bash
# docker-compose logs --tail=200  netfilter-mailcow
Attaching to mc_netfilter-mailcow_1
netfilter-mailcow_1  |   File "/usr/lib/python3.9/site-packages/iptc/ip6tc.py", line 606, in _init
netfilter-mailcow_1  |     self.refresh()
netfilter-mailcow_1  |   File "/usr/lib/python3.9/site-packages/iptc/ip4tc.py", line 1634, in refresh
netfilter-mailcow_1  |     raise IPTCError("can't initialize %s: %s" % (self.name,
netfilter-mailcow_1  | iptc.ip4tc.IPTCError: can't initialize filter: b'iptables who? (do you need to insmod?)'
netfilter-mailcow_1  | Clearing all bans
netfilter-mailcow_1  | Traceback (most recent call last):
netfilter-mailcow_1  |   File "/server.py", line 526, in <module>
netfilter-mailcow_1  |     clear()
netfilter-mailcow_1  |   File "/server.py", line 287, in clear
netfilter-mailcow_1  |     filter6_table = iptc.Table6(iptc.Table6.FILTER)
netfilter-mailcow_1  |   File "/usr/lib/python3.9/site-packages/iptc/ip6tc.py", line 589, in __new__
netfilter-mailcow_1  |     obj._init(name, autocommit)
netfilter-mailcow_1  |   File "/usr/lib/python3.9/site-packages/iptc/ip6tc.py", line 606, in _init
netfilter-mailcow_1  |     self.refresh()
netfilter-mailcow_1  |   File "/usr/lib/python3.9/site-packages/iptc/ip4tc.py", line 1634, in refresh
netfilter-mailcow_1  |     raise IPTCError("can't initialize %s: %s" % (self.name,
netfilter-mailcow_1  | iptc.ip4tc.IPTCError: can't initialize filter: b'iptables who? (do you need to insmod?)'
netfilter-mailcow_1  | Clearing all bans
netfilter-mailcow_1  | Traceback (most recent call last):
netfilter-mailcow_1  |   File "/server.py", line 526, in <module>
netfilter-mailcow_1  |     clear()
netfilter-mailcow_1  |   File "/server.py", line 287, in clear
netfilter-mailcow_1  |     filter6_table = iptc.Table6(iptc.Table6.FILTER)
netfilter-mailcow_1  |   File "/usr/lib/python3.9/site-packages/iptc/ip6tc.py", line 589, in __new__
netfilter-mailcow_1  |     obj._init(name, autocommit)
netfilter-mailcow_1  |   File "/usr/lib/python3.9/site-packages/iptc/ip6tc.py", line 606, in _init
netfilter-mailcow_1  |     self.refresh()
netfilter-mailcow_1  |   File "/usr/lib/python3.9/site-packages/iptc/ip4tc.py", line 1634, in refresh
netfilter-mailcow_1  |     raise IPTCError("can't initialize %s: %s" % (self.name,
netfilter-mailcow_1  | iptc.ip4tc.IPTCError: can't initialize filter: b'iptables who? (do you need to insmod?)'
netfilter-mailcow_1  | Clearing all bans

```

## Reproduction
i just call the update script.

## System information

```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo

uname -a
Linux mail 5.16.9-arch1-1 #1 SMP PREEMPT Fri, 11 Feb 2022 22:42:06 +0000 x86_64 GNU/Linux
```

| Question | Answer |
| --- | --- |
| My operating system | Arch Linux  (see above)|
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | kvm |
| Server/VM specifications (Memory, CPU Cores) |RAM: 8GiB RAM, CPU: 2 Intel Xeon Cores |
| Docker Version (`docker version`) | Docker version 20.10.12, build e91ed5707e|
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.29.2, build 5becea4c |
| Reverse proxy (custom solution) | no |

**Comment by bodsch** [comment]
my bloody solution ...

On Hostsystem:
```bash
modprobe -v ip6table_filter
insmod /lib/modules/5.16.9-arch1-1/kernel/net/ipv6/netfilter/ip6_tables.ko.zst 
insmod /lib/modules/5.16.9-arch1-1/kernel/net/ipv6/netfilter/ip6table_filter.ko.zst
```
and
```bash
docker-compose restart netfilter-mailcow
Restarting mc_netfilter-mailcow_1 ... done
```

and the container are up and running.

```bash
docker-compose logs --tail=20  netfilter-mailcow
Attaching to mc_netfilter-mailcow_1
netfilter-mailcow_1  |   File "/server.py", line 526, in <module>
netfilter-mailcow_1  |     clear()
netfilter-mailcow_1  |   File "/server.py", line 287, in clear
netfilter-mailcow_1  |     filter6_table = iptc.Table6(iptc.Table6.FILTER)
netfilter-mailcow_1  |   File "/usr/lib/python3.9/site-packages/iptc/ip6tc.py", line 589, in __new__
netfilter-mailcow_1  |     obj._init(name, autocommit)
netfilter-mailcow_1  |   File "/usr/lib/python3.9/site-packages/iptc/ip6tc.py", line 606, in _init
netfilter-mailcow_1  |     self.refresh()
netfilter-mailcow_1  |   File "/usr/lib/python3.9/site-packages/iptc/ip4tc.py", line 1634, in refresh
netfilter-mailcow_1  |     raise IPTCError("can't initialize %s: %s" % (self.name,
netfilter-mailcow_1  | iptc.ip4tc.IPTCError: can't initialize filter: b'iptables who? (do you need to insmod?)'
netfilter-mailcow_1  | Clearing all bans
netfilter-mailcow_1  | Initializing mailcow netfilter chain
netfilter-mailcow_1  | Watching Redis channel F2B_CHANNEL
netfilter-mailcow_1  | Whitelist was changed, it has 1 entries
netfilter-mailcow_1  | Clearing all bans
netfilter-mailcow_1  | Clearing all bans
netfilter-mailcow_1  | Initializing mailcow netfilter chain
netfilter-mailcow_1  | Watching Redis channel F2B_CHANNEL
netfilter-mailcow_1  | Whitelist was changed, it has 1 entries
```

But I think on a system without this kernel module, errors will occur again.

Error handling should be implemented here
```python
filter6_table = iptc.Table6(iptc.Table6.FILTER)
```

**Comment by atlanticfirst** [comment]
i've got same problem in CentOS Stream 9. it permanently restart even in a fresh installed centos stream 9

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
Same problem in Rocky 9

**Comment by tracure1337** [comment]
Same problem in Rocky 9

fixed in https://github.com/mailcow/mailcow-dockerized/issues/4802#issuecomment-1342460292
