### ISSUE TITLE
netfilter container is creating huge amount of the same SNAT rule for ipv4

### ISSUE THREAD

**Issue by mnin** [mailcow/mailcow-dockerized#4697]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

Hey,

just found a bug in the netfilter container.

Since using Alpine 3.16 (netfilter image version 1.48) it's not able to found the rule is already created in the chain/table.

With Alpine 3.15 (netfilter image version 1.47) it's still working fine.

### Logs

```bash
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
```

### Steps to reproduce

`SNAT_TO_SOURCE` needs to be filled in the mailcow.conf file.

Find needed variables:

```shell
docker-compose exec netfilter-mailcow sh

export | grep NETWORK
export | grep TO_SOURCE
```

Output:

```shell
/ # export | grep NETWORK
export IPV4_NETWORK='172.22.1'
export IPV6_NETWORK='fd4d:6169:6c63:6f77::/64'
/ # export | grep TO_SOURCE
export SNAT6_TO_SOURCE='...'
export SNAT_TO_SOURCE='...'
```

Use this export variables in the following testing statements to reproduce the behaviour.

# using different netfilter container image versions

# 1.47 with Alpine 3.15 working fine

```shell
docker run --privileged  --network host --rm -it mailcow/netfilter:1.47 sh

export IPV4_NETWORK='172.22.1'
export IPV6_NETWORK='fd4d:6169:6c63:6f77::/64'
export SNAT6_TO_SOURCE='...'
export SNAT_TO_SOURCE='...'

python3
```

Put this python script into the terminal:

```python
import os
import iptc

snat_target = os.getenv('SNAT_TO_SOURCE')

def get_snat4_rule():
  rule = iptc.Rule()
  rule.src = os.getenv('IPV4_NETWORK', '172.22.1') + '.0/24'
  rule.dst = '!' + rule.src
  target = rule.create_target("SNAT")
  target.to_source = snat_target
  return rule

rule = get_snat4_rule()

table = iptc.Table('nat')
table.refresh()
chain = iptc.Chain(table, 'POSTROUTING')
table.autocommit = False

iptc.easy.decode_iptc_rule(rule)
iptc.easy.decode_iptc_rule(chain.rules[0])

chain.rules[0].__eq__(rule)
```

Output:

```shell
>>> iptc.easy.decode_iptc_rule(rule)
{'src': '172.22.1.0/24', 'dst': '!172.22.1.0/24', 'target': {'SNAT': {'to-source': '...'}}, 'counters': (0, 0)}
>>> iptc.easy.decode_iptc_rule(chain.rules[0])
{'src': '172.22.1.0/24', 'dst': '!172.22.1.0/24', 'target': {'SNAT': {'to-source': '...'}}, 'counters': (0, 0)}
>>>
>>> chain.rules[0].__eq__(rule)
True
```

The `True` means, it can match the existing rule. It uses for testing purposes just the first rule in the chain `POSTROUTING` check it via `iptables -t nat -L POSTROUTING -nvx` directly in the terminal.

# 1.48 with Alpine 3.16 is not working

```shell
docker run --privileged  --network host --rm -it mailcow/netfilter:1.48 sh

export IPV4_NETWORK='172.22.1'
export IPV6_NETWORK='fd4d:6169:6c63:6f77::/64'
export SNAT6_TO_SOURCE='...'
export SNAT_TO_SOURCE='...'

python3
```

Put this python script into the terminal:

```python
import os
import iptc

snat_target = os.getenv('SNAT_TO_SOURCE')

def get_snat4_rule():
  rule = iptc.Rule()
  rule.src = os.getenv('IPV4_NETWORK', '172.22.1') + '.0/24'
  rule.dst = '!' + rule.src
  target = rule.create_target("SNAT")
  target.to_source = snat_target
  return rule

rule = get_snat4_rule()

table = iptc.Table('nat')
table.refresh()
chain = iptc.Chain(table, 'POSTROUTING')
table.autocommit = False

iptc.easy.decode_iptc_rule(rule)
iptc.easy.decode_iptc_rule(chain.rules[0])

chain.rules[0].__eq__(rule)
```

Output:

```shell
>>> iptc.easy.decode_iptc_rule(rule)
{'src': '172.22.1.0/24', 'dst': '!172.22.1.0/24', 'target': {'SNAT': {'to-source': '...'}}, 'counters': (0, 0)}
>>> iptc.easy.decode_iptc_rule(chain.rules[0])
{'src': '172.22.1.0/24', 'dst': '!172.22.1.0/24', 'target': {'SNAT': {'to-source': '...'}}, 'counters': (0, 0)}
>>>
>>> chain.rules[0].__eq__(rule)
False
```

The `False` means, it cannot match the existing rule. So it creates a new one every 10 seconds.

 It uses for testing purposes just the first rule in the chain `POSTROUTING` check it via `iptables -t nat -L POSTROUTING -nvx` directly in the terminal.

Reproduce directly with the Alpine image:

# Alpine 3.16 (not working)

```shell
docker run --privileged  --network host --rm -it alpine:3.16 sh

# from Dockerfile

export XTABLES_LIBDIR=/usr/lib/xtables
export PYTHON_IPTABLES_XTABLES_VERSION=12
export IPTABLES_LIBDIR=/usr/lib

apk add --virtual .build-deps \
  gcc \
  python3-dev \
  libffi-dev \
  openssl-dev \
&& apk add -U python3 \
  iptables \
  ip6tables \
  xtables-addons \
  tzdata \
  py3-pip \
  musl-dev \
&& pip3 install --ignore-installed --upgrade pip \
  python-iptables \
  redis \
  ipaddress \
  dnspython \
&& apk del .build-deps

export IPV4_NETWORK='172.22.1'
export IPV6_NETWORK='fd4d:6169:6c63:6f77::/64'
export SNAT6_TO_SOURCE='...'
export SNAT_TO_SOURCE='...'

python3
```

Put this python script into the terminal:

```python
import os
import iptc

snat_target = os.getenv('SNAT_TO_SOURCE')

def get_snat4_rule():
  rule = iptc.Rule()
  rule.src = os.getenv('IPV4_NETWORK', '172.22.1') + '.0/24'
  rule.dst = '!' + rule.src
  target = rule.create_target("SNAT")
  target.to_source = snat_target
  return rule

rule = get_snat4_rule()

table = iptc.Table('nat')
table.refresh()
chain = iptc.Chain(table, 'POSTROUTING')
table.autocommit = False

iptc.easy.decode_iptc_rule(rule)
iptc.easy.decode_iptc_rule(chain.rules[0])

chain.rules[0].__eq__(rule)
```

# Output

```shell
>>> iptc.easy.decode_iptc_rule(rule)
{'src': '172.22.1.0/24', 'dst': '!172.22.1.0/24', 'target': {'SNAT': {'to-source': '...'}}, 'counters': (0, 0)}
>>> iptc.easy.decode_iptc_rule(chain.rules[0])
{'src': '172.22.1.0/24', 'dst': '!172.22.1.0/24', 'target': {'SNAT': {'to-source': '...'}}, 'counters': (11, 808)}
>>>
>>> chain.rules[0].__eq__(rule)
False
```

False -> matching wasn't successful

# Alpine 3.15 (working)

```shell
docker run --privileged  --network host --rm -it alpine:3.15 sh

# from Dockerfile

export XTABLES_LIBDIR=/usr/lib/xtables
export PYTHON_IPTABLES_XTABLES_VERSION=12
export IPTABLES_LIBDIR=/usr/lib

apk add --virtual .build-deps \
  gcc \
  python3-dev \
  libffi-dev \
  openssl-dev \
&& apk add -U python3 \
  iptables \
  ip6tables \
  xtables-addons \
  tzdata \
  py3-pip \
  musl-dev \
&& pip3 install --ignore-installed --upgrade pip \
  python-iptables \
  redis \
  ipaddress \
  dnspython \
&& apk del .build-deps

export IPV4_NETWORK='172.22.1'
export IPV6_NETWORK='fd4d:6169:6c63:6f77::/64'
export SNAT6_TO_SOURCE='...'
export SNAT_TO_SOURCE='...'

python3
```

Put this python script into the terminal:

```python
import os
import iptc

snat_target = os.getenv('SNAT_TO_SOURCE')

def get_snat4_rule():
  rule = iptc.Rule()
  rule.src = os.getenv('IPV4_NETWORK', '172.22.1') + '.0/24'
  rule.dst = '!' + rule.src
  target = rule.create_target("SNAT")
  target.to_source = snat_target
  return rule

rule = get_snat4_rule()

table = iptc.Table('nat')
table.refresh()
chain = iptc.Chain(table, 'POSTROUTING')
table.autocommit = False

iptc.easy.decode_iptc_rule(rule)
iptc.easy.decode_iptc_rule(chain.rules[0])

chain.rules[0].__eq__(rule)
```

# Output

```shell
>>> iptc.easy.decode_iptc_rule(rule)
{'src': '172.22.1.0/24', 'dst': '!172.22.1.0/24', 'target': {'SNAT': {'to-source': '...'}}, 'counters': (0, 0)}
>>> iptc.easy.decode_iptc_rule(chain.rules[0])
{'src': '172.22.1.0/24', 'dst': '!172.22.1.0/24', 'target': {'SNAT': {'to-source': '...'}}, 'counters': (0, 0)}
>>>
>>> chain.rules[0].__eq__(rule)
True
```

True -> matching was successful as expected.

### System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04 LTS |
| Is Apparmor, SELinux or similar active? | I_DO_REPLY_HERE |
| Virtualization technology (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | nope |
| Server/VM specifications (Memory, CPU Cores) | I_DO_REPLY_HERE |
| Docker version (`docker version`) | 20.10.17 |
| docker-compose version (`docker-compose version`) | v2.7.0 |
| mailcow version (```git describe --tags `git rev-list --tags --max-count=1` ```) | 2022-07 |
| Reverse proxy (custom solution) | nope |

**Comment by ghost** [comment]
Duplicate #4658, maybe search for open issue before creating new one? :)

**Comment by mnin** [comment]
@mthld thanks, didn't saw it in the search.. I will continue describing the stuff here to reproduce..

**Comment by andryyy** [comment]
The fix would be to replace...

```
table = iptc.Table('nat')
table.refresh()
chain = iptc.Chain(table, 'POSTROUTING')
table.autocommit = False
if get_snat4_rule() not in chain.rules:
  log['time'] = int(round(time.time()))
  log['priority'] = 'info'
  log['message'] = 'Added POSTROUTING rule for source network ' + get_snat4_rule().src + ' to SNAT target ' + snat_target
  r.lpush('NETFILTER_LOG', json.dumps(log, ensure_ascii=False))
  print log['message']
  chain.insert_rule(get_snat4_rule())
  table.commit()
```

...by...

```
table = iptc.Table('nat')
table.refresh()
chain = iptc.Chain(table, 'POSTROUTING')
table.autocommit = False
for r in chain.rules:
  if r.get_src() != rule.get_src() and \
    r.get_dst() != rule.get_dst() and \
    r.target.parameters != rule.target.parameters and \
    r.target.name != rule.target.name:
      log['time'] = int(round(time.time()))
      log['priority'] = 'info'
      log['message'] = 'Added POSTROUTING rule for source network ' + get_snat4_rule().src + ' to SNAT target ' + snat_target
      r.lpush('NETFILTER_LOG', json.dumps(log, ensure_ascii=False))
      print log['message']
      chain.insert_rule(get_snat4_rule())
      table.commit()
```

Better to do it for v4 and v6.

**Comment by andryyy** [comment]
Hmm, that would add the rule even when the first SNAT rule is not ours. I mean, we will insert it (on top), so the loop would always be okay. But if something else is adding SNAT rules without noticing we will end up with a full chain.

Perhaps we should delete the SNAT rule before adding "our" rule.

**Comment by andryyy** [comment]
We could also loop with if bla1 == bla2 instead of bla1 != bla2 and break the loop if it matches. Then we should check the position of the rule and perhaps remove it and re-add it?

Some other rule __might__ interfere with ours when it's above ours.

**Comment by mnin** [comment]
> 

when I try to delete the rule from the chain I got this output:

```shell
>>> table.commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/iptc/ip4tc.py", line 1612, in commit
    raise IPTCError("can't commit: %s" % (self.strerror()))
iptc.ip4tc.IPTCError: can't commit: b'Resource temporarily unavailable'
```

**Comment by mnin** [comment]
sounds like this code can be helpful https://github.com/ldx/python-iptables/blob/master/iptc/ip4tc.py#L967-L972

might be also possible to add a `mailcow` specific comment to the rule and search for this comment?

**Comment by mnin** [comment]
maybe usage of `iptc.easy.decode_iptc_rule(rule)` and comparing the return value of it (except the counters) would do the same

**Comment by andryyy** [comment]
Test with `log['message'] = 'Added POSTROUTING SNAT rule to source ' + snat_target`, please. "snat_target" should also be source actually. :)

I would also like to discuss my proposed changes above and how to handle existing rules.

I'd vote for keeping existing rules, set a flag like "snat_cow = { "found": True, "position": n}` or whatever status it has and act on it.

**Comment by mnin** [comment]
```python
table = iptc.Table('nat')
table.refresh()
chain = iptc.Chain(table, 'POSTROUTING')
table.autocommit = False
for r in chain.rules:
  if r.get_src() != rule.get_src() and \
    r.get_dst() != rule.get_dst() and \
    r.target.parameters != rule.target.parameters and \
    r.target.name != rule.target.name:
      log['time'] = int(round(time.time()))
      log['priority'] = 'info'
      log['message'] = 'Added POSTROUTING rule for source network ' + get_snat4_rule().src + ' to SNAT target ' + snat_target
      r.lpush('NETFILTER_LOG', json.dumps(log, ensure_ascii=False))
      print(log['message'])
      chain.insert_rule(get_snat4_rule())
        table.commit()
```

looks working fine

**Comment by amorfo77** [comment]
`
        table = iptc.Table('nat')
        table.refresh()
        chain = iptc.Chain(table, 'POSTROUTING')
        table.autocommit = False
        our_rule = get_snat4_rule()
        for position, rule in enumerate(chain.rules):
          match = all((
                our_rule.get_src() == rule.get_src(),
                our_rule.get_dst() == rule.get_dst(),
                our_rule.target.parameters == rule.target.parameters,
                our_rule.target.name == rule.target.name
          ))
          if position == 0:
            if not match:
              logCrit(f'Added POSTROUTING rule for source network {our_rule.src} to SNAT target {snat_target}')
              chain.insert_rule(our_rule)
          else:
            if match:
              chain.delete_rule(our_rule)
        table.commit()
        table.autocommit = True
`
that code worked for me

**Comment by amorfo77** [comment]
```python
      try:
        table = iptc.Table('nat')
        table.refresh()
        chain = iptc.Chain(table, 'POSTROUTING')
        table.autocommit = False
        our_rule = get_snat4_rule()
        for position, rule in enumerate(chain.rules):
          match = all((
                our_rule.get_src() == rule.get_src(),
                our_rule.get_dst() == rule.get_dst(),
                our_rule.target.parameters == rule.target.parameters,
                our_rule.target.name == rule.target.name
          ))
          if position == 0:
            if not match:
              logCrit(f'Added POSTROUTING rule for source network {our_rule.src} to SNAT target {snat_target}')
              chain.insert_rule(our_rule)
          else:
            if match:
              chain.delete_rule(our_rule)
        table.commit()
        table.autocommit = True
      except:
        print('Error running SNAT4, retrying...')
```
in my testing machine, that code worked fine

**Comment by milkmaker** [comment]
This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by MAGICCC** [comment]
We'll close it when its in master with the next release

**Comment by MAGICCC** [comment]
Released in https://github.com/mailcow/mailcow-dockerized/releases/tag/2022-10
