### ISSUE TITLE
Mailcow Admin UI after login bugged

### ISSUE THREAD

**Issue by JackTheKipper** [mailcow/mailcow-dockerized#4704]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

Hello,

we have the problem that, after using update.sh the admin gui had a overlay on top of it so you couldnt click anything, after getting rid of that we can finally log in, but the site that appears right after the login cant be used, nothing happens when you click the buttons, only "reload sogo" and "quarantine" work and when on "quarantine" I can click the "configuration" button.

If you need more information to help, just ask.

Thanks!

### Logs

```bash
I dont know wich logs would be helpful for that kind of problem
```

### Steps to reproduce

1. update from 1.13 to newest version

### System information

| Question | Answer |
| --- | --- |
| My operating system | Debian 9 |
| Is Apparmor, SELinux or similar active? | I_DO_REPLY_HERE |
| Virtualization technology (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | I_DO_REPLY_HERE |
| Server/VM specifications (Memory, CPU Cores) | I_DO_REPLY_HERE |
| Docker version (`docker version`) | I_DO_REPLY_HERE |
| docker-compose version (`docker-compose version`) | I_DO_REPLY_HERE |
| mailcow version (```git describe --tags `git rev-list --tags --max-count=1` ```) | I_DO_REPLY_HERE |
| Reverse proxy (custom solution) | I_DO_REPLY_HERE |

Output of `git diff origin/master`, any other changes to the code? If so, **please post them**:
```
YOUR OUTPUT GOES HERE
```

All third-party firewalls and custom iptables rules are unsupported. **Please check the Docker docs about how to use Docker with your own ruleset**. Nevertheless, iptabels output can help us to help you:
iptables -L -vn:
```
YOUR OUTPUT GOES HERE
```

ip6tables -L -vn:
```
YOUR OUTPUT GOES HERE
```

iptables -L -vn -t nat:
```
YOUR OUTPUT GOES HERE
```

ip6tables -L -vn -t nat:
```
YOUR OUTPUT GOES HERE
```

DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output:
```
YOUR OUTPUT GOES HERE
```

**Comment by andryyy** [comment]
Hi, can you post the debug console output of your browser? Please also try to clean the cache (tm) and stuff.

**Comment by MAGICCC** [comment]
Also use the whole template, there are some things missing, e.g. output of git diff origin/master

**Comment by JackTheKipper** [comment]
> Hi, can you post the debug console output of your browser? Please also try to clean the cache (tm) and stuff.

Console Output:
`
```
JQMIGRATE: Migrate is installed, version 3.1.0
4953cbb54045796b055d4a7220df4b0c1cd41410.js:2 jQuery.Deferred exception: lang_footer is not defined ReferenceError: lang_footer is not defined
    at HTMLDocument.<anonymous> (http://172.16.81.99/cache/4953cbb54045796b055d4a7220df4b0c1cd41410.js:112:250)
    at e (http://172.16.81.99/cache/4953cbb54045796b055d4a7220df4b0c1cd41410.js:2:29453)
    at t (http://172.16.81.99/cache/4953cbb54045796b055d4a7220df4b0c1cd41410.js:2:29755) undefined
k.Deferred.exceptionHook @ 4953cbb54045796b055d4a7220df4b0c1cd41410.js:2
t @ 4953cbb54045796b055d4a7220df4b0c1cd41410.js:2
setTimeout (async)
(anonymous) @ 4953cbb54045796b055d4a7220df4b0c1cd41410.js:2
c @ 4953cbb54045796b055d4a7220df4b0c1cd41410.js:2
fireWith @ 4953cbb54045796b055d4a7220df4b0c1cd41410.js:2
fire @ 4953cbb54045796b055d4a7220df4b0c1cd41410.js:2
c @ 4953cbb54045796b055d4a7220df4b0c1cd41410.js:2
fireWith @ 4953cbb54045796b055d4a7220df4b0c1cd41410.js:2
ready @ 4953cbb54045796b055d4a7220df4b0c1cd41410.js:2
B @ 4953cbb54045796b055d4a7220df4b0c1cd41410.js:2
4953cbb54045796b055d4a7220df4b0c1cd41410.js:112 Uncaught ReferenceError: lang_footer is not defined
    at HTMLDocument.<anonymous> (4953cbb54045796b055d4a7220df4b0c1cd41410.js:112)
    at e (4953cbb54045796b055d4a7220df4b0c1cd41410.js:2)
    at t (4953cbb54045796b055d4a7220df4b0c1cd41410.js:2)
```
`
Output git diff origin/master:

```
git diff origin/master
diff --git a/.env b/.env
deleted file mode 120000
index 9400869f..00000000
--- a/.env
+++ /dev/null
@@ -1 +0,0 @@
-mailcow.conf
\ No newline at end of file
diff --git a/.env b/.env
new file mode 100644
index 00000000..5f8366f5
--- /dev/null
+++ b/.env
@@ -0,0 +1,237 @@
+# ------------------------------
+# mailcow web ui configuration
+# ------------------------------
+# example.org is _not_ a valid hostname, use a fqdn here.
+# Default admin user is "admin"
+# Default password is "moohoo"
+
+MAILCOW_HOSTNAME=XY
+
+# Password hash algorithm
+# Only certain password hash algorithm are supported. For a fully list of supported schemes,
+# see https://mailcow.github.io/mailcow-dockerized-docs/model-passwd/
+MAILCOW_PASS_SCHEME=BLF-CRYPT
+
+# ------------------------------
+# SQL database configuration
+# ------------------------------
+
+DBNAME=mailcow
+DBUSER=mailcow
+
+# Please use long, random alphanumeric strings (A-Za-z0-9)
+
+
+# ------------------------------
+# HTTP/S Bindings
+# ------------------------------
:
```


sorry it took so long!

**Comment by andryyy** [comment]
Isn't there more? The `:` indicates that.

Can you try to run `docker compose down` (or `docker-compose`) followed by:

```
git fetch origin master
git checkout origin/master data/web
```

`docker compose up -d`

**Comment by JackTheKipper** [comment]
Yeah there is more, where should i make the cut?  The output is never ending....

root@vm-linux-demo:/opt/mailcow# git fetch origin master
Von https://github.com/mailcow/mailcow-dockerized
 * branch              master     -> FETCH_HEAD

git checkout origin/master data/web has no output

**Comment by milkmaker** [comment]
This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.
