### ISSUE TITLE
Anonymous TLS connection established

### ISSUE THREAD

**Issue by martster** [mailcow/mailcow-dockerized#492]
Hi guys,
thanks for having mailcow! :)
Nevertheless, I am in trouble. From an app called Wekan I try to send Notifications which doesn't work. The mailcowdockerized-postfix logs say the following: 

```

Aug  4 14:36:02 mail-domain syslog-ng[8]: syslog-ng starting up; version='3.8.1'
Aug  4 14:36:03 mail-domain postfix[229]: Postfix is running with backwards-compatible default settings
Aug  4 14:36:03 mail-domain postfix[229]: See http://www.postfix.org/COMPATIBILITY_README.html for details
Aug  4 14:36:03 mail-domain postfix[229]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
Aug  4 14:36:03 mail-domain postfix/postfix-script[316]: starting the Postfix mail system
Aug  4 14:36:03 mail-domain postfix/master[318]: daemon started -- version 3.1.4, configuration /opt/postfix/conf
2017-08-04 14:36:03,952 INFO success: postfix entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-08-04 14:36:03,952 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Aug  4 14:36:13 mail-domain postfix/postscreen[324]: CONNECT from [172.22.1.1]:46352 to [172.22.1.3]:25
Aug  4 14:36:13 mail-domain postfix/postscreen[324]: WHITELISTED [172.22.1.1]:46352
Aug  4 14:36:13 mail-domain postfix/smtpd[327]: connect from unknown[172.22.1.1]
Aug  4 14:36:13 mail-domain postfix/smtpd[327]: Anonymous TLS connection established from unknown[172.22.1.1]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Aug  4 14:36:13 mail-domain postfix/smtpd[327]: lost connection after STARTTLS from unknown[172.22.1.1]
Aug  4 14:36:13 mail-domain postfix/smtpd[327]: disconnect from unknown[172.22.1.1] ehlo=1 starttls=1 commands=2
Aug  4 14:36:21 mail-domain postfix/postscreen[324]: CONNECT from [172.22.1.1]:46366 to [172.22.1.3]:25
Aug  4 14:36:21 mail-domain postfix/postscreen[324]: WHITELISTED [172.22.1.1]:46366
Aug  4 14:36:21 mail-domain postfix/smtpd[327]: connect from unknown[172.22.1.1]
Aug  4 14:36:21 mail-domain postfix/smtpd[327]: Anonymous TLS connection established from unknown[172.22.1.1]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Aug  4 14:36:21 mail-domain postfix/smtpd[327]: lost connection after STARTTLS from unknown[172.22.1.1]
Aug  4 14:36:21 mail-domain postfix/smtpd[327]: disconnect from unknown[172.22.1.1] ehlo=1 starttls=1 commands=2
```

I have no idea what am I doing wrong. I set up an user with a password for sending the notifications and I told the app to use this. I also configured Wekan to use mail.domain.tld as SMTP-server where mailcow is installed.  
Could anybody advise me who to configure mailcow right?

**Comment by lazyfrosch** [comment]
Looks like the client doesn't like the TLS connection, or certificate.

Does Wekan log anything?

**Comment by lazyfrosch** [comment]
https://github.com/wekan/wekan/issues/1120 ?

**Comment by martster** [comment]
@lazyfrosch The Logs say the following:
```
Exception while invoking method 'forgotPassword' Error: unable to verify the first certificate
    at Object.Future.wait (/build/programs/server/node_modules/fibers/future.js:449:15)
    at Mail._syncSendMail (packages/meteor.js:213:24)
    at smtpSend (packages/email.js:116:13)
    at Object.Email.send (packages/email.js:174:5)
    at AccountsServer.Accounts.sendResetPasswordEmail (packages/accounts-password/password_server.js:614:9)
    at [object Object].Meteor.methods.forgotPassword (packages/accounts-password/password_server.js:546:12)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
    at packages/ddp-server/livedata_server.js:719:19
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:717:40
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:715:46
    at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
    - - - - -
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1065:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:623:8)
    at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:453:38)
```

In wekan/wekan#1120 they refer to snap. But I installed Wekan via Docker.

**Comment by lazyfrosch** [comment]
The problem is basically the same in named issue:

    Exception while invoking method 'forgotPassword' Error: unable to verify the first certificate

Looks like Wekan is not trusting your certificate, so thats your problem.

Probably ca-certificates is not installed correctly or whatever. **But** this is not a problem of mailcow.

**Comment by martster** [comment]
The hint that the ca-certificates aren't installed correctly or whatever is slightly unspecific. I installed the certificates with Certbot. Do I have to configure something else in Mailcow? I can reach the Mailcow frontend via https in browser without any problems. Mailcow runs behind an Apache Proxy Server.

**Comment by lazyfrosch** [comment]
`ca-certificates` is a typical OS package containing all the trusted root certificates.

Wekan seems to install it: https://hub.docker.com/r/wekanteam/wekan/~/dockerfile/

The NodeJS of Wekan is not trusting your Mailserver's TLS. But this is a Wekan problem, I'm not sure how to help.
