### ISSUE TITLE
Domains and Mailboxes not showing after updaring to 2022-12b

### ISSUE THREAD

**Issue by marcozink** [mailcow/mailcow-dockerized#4946]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
After updating to 2022-12b I can no longer see the configured domains nor the mailboxes. This is a similar issue to #4921, looks like an issue with datatables, but the previous errors were fixed in this version.

All languages show this behavior.
```

### Logs:

```plain text
mailbox:2403 Uncaught SyntaxError: Unexpected token ';' (at mailbox:2403:33)
mailbox:1 [DOM] Found 2 elements with non-unique id #addMailbox_tags: (More info: https://goo.gl/9p2vKq) input#addMailbox_tags.tag-input input#addMailbox_tags.tag-input
mailbox:1 [DOM] Found 2 elements with non-unique id #dkim_selector: (More info: https://goo.gl/9p2vKq) input#dkim_selector.form-control input#dkim_selector.form-control
mailbox:1 [DOM] Found 2 elements with non-unique id #key_size: (More info: https://goo.gl/9p2vKq) select#key_size.form-control select#key_size.form-control
df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2 jQuery.Deferred exception: acl is not defined ReferenceError: acl is not defined
    at HTMLDocument.<anonymous> (https://mail.zink.services/cache/df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2721:164)
    at e (https://mail.zink.services/cache/df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2:30038)
    at t (https://mail.zink.services/cache/df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2:30340) undefined
S.Deferred.exceptionHook @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
t @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
setTimeout (async)
(anonymous) @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
c @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
fireWith @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
fire @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
c @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
fireWith @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
ready @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
B @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2823 Uncaught ReferenceError: lang is not defined
    at df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2823:1217
    at Array.forEach (<anonymous>)
    at Object.complete (df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2823:1077)
    at c (df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2:28327)
    at Object.fireWith (df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2:29072)
    at l (df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2:80029)
    at XMLHttpRequest.<anonymous> (df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2:82355)
(anonymous) @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2823
complete @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2823
c @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
fireWith @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
l @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
(anonymous) @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
load (async)
send @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
ajax @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
(anonymous) @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2823
df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2721 Uncaught ReferenceError: acl is not defined
    at HTMLDocument.<anonymous> (df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2721:164)
    at e (df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2:30038)
    at t (df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2:30340)
(anonymous) @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2721
e @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
t @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
setTimeout (async)
S.readyException @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
(anonymous) @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
e @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
t @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
setTimeout (async)
(anonymous) @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
c @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
fireWith @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
fire @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
c @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
fireWith @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
t @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
setTimeout (async)
(anonymous) @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
c @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
fireWith @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
fire @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
c @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
fireWith @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
ready @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
B @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2
df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2775 Uncaught ReferenceError: lang_datatables is not defined
    at draw_mailbox_table (df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2775:83)
    at df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2823:169
    at df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2822:1503
    at Array.forEach (<anonymous>)
    at IntersectionObserver.<anonymous> (df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2822:1457)
draw_mailbox_table @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2775
(anonymous) @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2823
(anonymous) @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2822
(anonymous) @ df03e52b0360c2cd2e1a8c72ce97095ff8247eb0.js:2822
```

### Steps to reproduce:

```plain text
1. Update to 2022-12b using the update.sh script
2. Log in to the web-ui and go to E-mail->Configuration
3. No domains, no mailboxex
```

### Which branch are you using?

master

### Operating System:

Debian 11.6

### Server/VM specifications:

8GB, 2CPUs dedicated server

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

not virtualized

### Docker version:

20.10.22

### docker-compose version or docker compose version:

v2.9.0

### mailcow version:

2022-12b

### Reverse proxy:

nginx

### Logs of git diff:

```plain text
diff --git a/data/web/mailbox.php b/data/web/mailbox.php
index 65c76f53..346faebf 100644
--- a/data/web/mailbox.php
+++ b/data/web/mailbox.php
@@ -35,7 +35,7 @@ $template_data = [
   'acl_json' => json_encode($_SESSION['acl']),
   'role' => $role,
   'is_dual' => $is_dual,
-  'allow_admin_email_login' => $allow_admin_email_login,
+  'allow_admin_email_login_roundcube' => (preg_match("/^(yes|y)+$/i", $_ENV["ALLOW_ADMIN_EMAIL_LOGIN_R
OUNDCUBE"])) ? 'true' : 'false',
   'global_filters' => mailbox('get', 'global_filter_details'),
   'domains' => $domains,
   'mailboxes' => $mailboxes,
diff --git a/data/web/templates/mailbox.twig b/data/web/templates/mailbox.twig
index cdb6a428..bb59c5c3 100644
--- a/data/web/templates/mailbox.twig
+++ b/data/web/templates/mailbox.twig
@@ -62,5 +62,6 @@
   var role = '{{ role }}';
   var is_dual = {{ is_dual }};
   var ALLOW_ADMIN_EMAIL_LOGIN = {{ allow_admin_email_login }};
+  var ALLOW_ADMIN_EMAIL_LOGIN_ROUNDCUBE = {{ allow_admin_email_login_roundcube }};
 </script>
 {% endblock %}
diff --git a/docker-compose.yml b/docker-compose.yml
index b940b336..5f6c4110 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -583,36 +583,6 @@ services:
           aliases:
             - ofelia


-    ipv6nat-mailcow:
-      depends_on:
-        - unbound-mailcow
-        - mysql-mailcow
-        - redis-mailcow
-        - clamd-mailcow
-        - rspamd-mailcow
-        - php-fpm-mailcow
-        - sogo-mailcow
-        - dovecot-mailcow
-        - postfix-mailcow
-        - memcached-mailcow
-        - nginx-mailcow
-        - acme-mailcow
-        - netfilter-mailcow
-        - watchdog-mailcow
-        - dockerapi-mailcow
-        - solr-mailcow
-      environment:
-        - TZ=${TZ}
-      image: robbertkl/ipv6nat
-      security_opt:
-        - label=disable
-      restart: always
-      privileged: true
-      network_mode: "host"
-      volumes:
-        - /var/run/docker.sock:/var/run/docker.sock:ro
-        - /lib/modules:/lib/modules:ro
-
 networks:
   mailcow-network:
     driver: bridge
```

### Logs of iptables -L -vn:

```plain text
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy DROP 1 packets, 60 bytes)
 pkts bytes target     prot opt in     out     source               destination
2752K  877M DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0
2752K  877M DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0
2085K  640M ACCEPT     all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
 177K   11M DOCKER     all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0
 490K  226M ACCEPT     all  --  br-mailcow !br-mailcow  0.0.0.0/0            0.0.0.0/0
 158K 9818K ACCEPT     all  --  br-mailcow br-mailcow  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination
  166  8836 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.3           tcp dpt:8080
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.249         tcp dpt:6379
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.9           tcp dpt:8983
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.11          tcp dpt:3306
  345 18076 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:587
   78  4628 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:465
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:12345
    4   220 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:4190
 1430 85560 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:25
  121  6914 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:995
 9448  567K ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:993
 1483 88932 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:143
 1494 89408 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:110
 2403  145K ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.13          tcp dpt:443
 1664 98111 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.13          tcp dpt:80

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination
 490K  226M DOCKER-ISOLATION-STAGE-2  all  --  br-mailcow !br-mailcow  0.0.0.0/0            0.0.0.0/0
    0     0 DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
3060K  974M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0
    0     0 DROP       all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
 547K  254M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination
  95M   31G RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
```

### Logs of ip6tables -L -vn:

```plain text
# Warning: ip6tables-legacy tables present, use ip6tables-legacy to see them
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
 372K  402M DOCKER-ISOLATION-STAGE-1  all      *      *       ::/0                 ::/0
 291K  397M ACCEPT     all      *      br-mailcow  ::/0                 ::/0                 ctstate RELATED,ESTABLISHED
80872 5645K DOCKER     all      *      br-mailcow  ::/0                 ::/0
    0     0 ACCEPT     all      br-mailcow !br-mailcow  ::/0                 ::/0
80872 5645K ACCEPT     all      br-mailcow br-mailcow  ::/0                 ::/0
    0     0 ACCEPT     all      *      docker0  ::/0                 ::/0                 ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all      *      docker0  ::/0                 ::/0
    0     0 ACCEPT     all      docker0 !docker0  ::/0                 ::/0
    0     0 ACCEPT     all      docker0 docker0  ::/0                 ::/0

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::3  tcp dpt:8080
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::11  tcp dpt:587
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::11  tcp dpt:465
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::12  tcp dpt:4190
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::11  tcp dpt:25
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::12  tcp dpt:995
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::12  tcp dpt:993
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::12  tcp dpt:143
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::12  tcp dpt:110
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::10  tcp dpt:443
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::10  tcp dpt:80

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER-ISOLATION-STAGE-2  all      br-mailcow !br-mailcow  ::/0                 ::/0
    0     0 DOCKER-ISOLATION-STAGE-2  all      docker0 !docker0  ::/0                 ::/0
 433K  476M RETURN     all      *      *       ::/0                 ::/0

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all      *      br-mailcow  ::/0                 ::/0
    0     0 DROP       all      *      docker0  ::/0                 ::/0
    0     0 RETURN     all      *      *       ::/0                 ::/0
```

### Logs of iptables -L -vn -t nat:

```plain text
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
76097 4193K DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
 159K   12M MASQUERADE  all  --  *      !br-mailcow  172.22.1.0/24        0.0.0.0/0
    0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.3           172.22.1.3           tcp dpt:8080
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.249         172.22.1.249         tcp dpt:6379
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.9           172.22.1.9           tcp dpt:8983
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.11          172.22.1.11          tcp dpt:3306
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.253         172.22.1.253         tcp dpt:587
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.253         172.22.1.253         tcp dpt:465
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:12345
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:4190
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.253         172.22.1.253         tcp dpt:25
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:995
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:993
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:143
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:110
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.13          172.22.1.13          tcp dpt:443
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.13          172.22.1.13          tcp dpt:80

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination
   10   600 RETURN     all  --  br-mailcow *       0.0.0.0/0            0.0.0.0/0
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0
  166  8836 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8080 to:172.22.1.3:8080
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:7654 to:172.22.1.249:6379
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:18983 to:172.22.1.9:8983
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:13306 to:172.22.1.11:3306
  345 18076 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:587 to:172.22.1.253:587
   78  4628 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:465 to:172.22.1.253:465
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:19991 to:172.22.1.250:12345
    4   220 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:4190 to:172.22.1.250:4190
 1430 85560 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:25 to:172.22.1.253:25
  121  6914 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:995 to:172.22.1.250:995
 9452  567K DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:993 to:172.22.1.250:993
 1483 88932 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:143 to:172.22.1.250:143
 1494 89408 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:110 to:172.22.1.250:110
 2404  145K DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443 to:172.22.1.13:443
 1665 98171 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:172.22.1.13:80
```

### Logs of ip6tables -L -vn -t nat:

```plain text
# Warning: ip6tables-legacy tables present, use ip6tables-legacy to see them
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER     all      *      *       ::/0                 ::/0                 ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER     all      *      *       ::/0                !::1                  ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 MASQUERADE  all      *      !br-mailcow  fd4d:6169:6c63:6f77::/64  ::/0
    0     0 MASQUERADE  all      *      !docker0  fd00:dead:beef:c0::/80  ::/0
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::3  fd4d:6169:6c63:6f77::3  tcp dpt:8080
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::11  fd4d:6169:6c63:6f77::11  tcp dpt:587
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::11  fd4d:6169:6c63:6f77::11  tcp dpt:465
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::12  fd4d:6169:6c63:6f77::12  tcp dpt:4190
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::11  fd4d:6169:6c63:6f77::11  tcp dpt:25
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::12  fd4d:6169:6c63:6f77::12  tcp dpt:995
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::12  fd4d:6169:6c63:6f77::12  tcp dpt:993
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::12  fd4d:6169:6c63:6f77::12  tcp dpt:143
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::12  fd4d:6169:6c63:6f77::12  tcp dpt:110
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::10  fd4d:6169:6c63:6f77::10  tcp dpt:443
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::10  fd4d:6169:6c63:6f77::10  tcp dpt:80

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 RETURN     all      br-mailcow *       ::/0                 ::/0
    0     0 RETURN     all      docker0 *       ::/0                 ::/0
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:8080 to:[fd4d:6169:6c63:6f77::3]:8080
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:587 to:[fd4d:6169:6c63:6f77::11]:587
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:465 to:[fd4d:6169:6c63:6f77::11]:465
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:4190 to:[fd4d:6169:6c63:6f77::12]:4190
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:25 to:[fd4d:6169:6c63:6f77::11]:25
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:995 to:[fd4d:6169:6c63:6f77::12]:995
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:993 to:[fd4d:6169:6c63:6f77::12]:993
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:143 to:[fd4d:6169:6c63:6f77::12]:143
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:110 to:[fd4d:6169:6c63:6f77::12]:110
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:443 to:[fd4d:6169:6c63:6f77::10]:443
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:80 to:[fd4d:6169:6c63:6f77::10]:80
```

### DNS check:

```plain text
151.101.193.69
151.101.1.69
151.101.65.69
151.101.129.69
```

**Comment by tomudding** [comment]
Based on your diff I think this is caused by a configuration mistake. You remove `'allow_admin_email_login'` from `data/web/mailbox.php` to add `allow_admin_email_login_roundcube`. However, in `data/web/templates/mailbox.twig` you do not remove the mention of `allow_admin_email_login`, causing the JavaScript variable `ALLOW_ADMIN_EMAIL_LOGIN` to be nothing breaking all variables in that `<script>` tag.

You essentially get something like:

```html
<script>
    // ....
    var role = 'some role';
    var is_dual = {};
    var ALLOW_ADMIN_EMAIL_LOGIN = ;
    var ALLOW_ADMIN_EMAIL_LOGIN_ROUNDCUBE = true;
 </script>
```

Which is invalid JavaScript, subsequently, all other scripts (such as DataTables) cannot use those variables and break too.

 Can you add

```php
'allow_admin_email_login' => $allow_admin_email_login,
```

back to `data/web/mailbox.php` and test whether everything works as expected? You could also remove `ALLOW_ADMIN_EMAIL_LOGIN` and all its mentions, but that is cumbersome (as it mentioned a lot in the JavaScript files).

**Comment by MAGICCC** [comment]
Maybe needs some docs updates then?
https://docs.mailcow.email/third_party/roundcube/third_party-roundcube/#let-admins-log-into-roundcube-without-password

**Comment by tomudding** [comment]
> Maybe needs some docs updates then? https://docs.mailcow.email/third_party/roundcube/third_party-roundcube/#let-admins-log-into-roundcube-without-password

The docs say "Edit `data/web/mailbox.php` and add this line to array `$template_data`:". So I do not think they need to be updated per se. However, making it more clear that you should not remove something is always a good idea.

I already opened mailcow/mailcow-dockerized-docs#506 to fix a mistake that will also cause problems with the newer releases.

**Comment by marcozink** [comment]
Ok, so yeah, looks like adding that line fixed the issue. I think I removed it by mistake when following comments on #4921, I had the previous code that didn't have the preg_match().
