### ISSUE TITLE
SOGo Save Button Glitch in the Mail Settings Panel does not work 

### ISSUE THREAD

**Issue by foto2004immi** [mailcow/mailcow-dockerized#5375]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Save button in the "E-mail settings" section reacts in reverse.

I noticed when we were setting up MailCow and we wanted to set up mail forwarding that the Save button is active when you call up the forwarding settings, but as soon as you tick the box that forwarding is active, it becomes inactive. 

It had already worked with another mailbox and then I updated MailCow and since then the error occurs with a newly created mailbox in the same domain.
```

### Logs:

```plain text
na
```

### Steps to reproduce:

```plain text
1. Logging into SOGo
2. go to the settings
3. go to the email settings 
4. then click on forwarding
5. check the Forward incoming messages box. the save icon turns grey, even if a correct email 
is specified.
6. uncheck Forward incoming messages. The save symbol becomes active again.
```

### Which branch are you using?

master

### Operating System:

Debian 12

### Server/VM specifications:

6000/4

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

Proxmox VM

### Docker version:

24.0.5

### docker-compose version or docker compose version:

v2.20.2

### mailcow version:

2023-08

### Reverse proxy:

nginx

### Logs of git diff:

```plain text
na
```

### Logs of iptables -L -vn:

```plain text
na
```

### Logs of ip6tables -L -vn:

```plain text
na
```

### Logs of iptables -L -vn -t nat:

```plain text
na
```

### Logs of ip6tables -L -vn -t nat:

```plain text
na
```

### DNS check:

```plain text
na
```

**Comment by sriccio** [comment]
Hello, discovered the very same issue today, with up-to-date mailcow installation.

Browser console shows:

```
activeExternalSieveScripts:1     Failed to load resource: the server responded with a status of 404 ()
PreferencesController.js:678 Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at e.addRecipient (PreferencesController.js:678:35)
    at fn (eval at compile (angular.js:16548:15), <anonymous>:4:246)
    at d.<computed> [as transformChip] (angular.js:11517:22)
    at e.appendChip (angular-material.min.js?lm=1690798532:7:195163)
    at e.onInputBlur (angular-material.min.js?lm=1690798532:7:198559)
    at HTMLInputElement.<anonymous> (angular.js:1391:15)
    at xg (angular.js:3891:3)
    at HTMLInputElement.d (angular.js:3879:9)
PreferencesController.js:678 Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at e.addRecipient (PreferencesController.js:678:35)
    at fn (eval at compile (angular.js:16548:15), <anonymous>:4:246)
    at d.<computed> [as transformChip] (angular.js:11517:22)
    at e.appendChip (angular-material.min.js?lm=1690798532:7:195163)
    at e.onInputBlur (angular-material.min.js?lm=1690798532:7:198559)
    at HTMLInputElement.<anonymous> (angular.js:1391:15)
    at xg (angular.js:3891:3)
    at HTMLInputElement.d (angular.js:3879:9)
angular.js:15697 TypeError: Cannot read properties of undefined (reading 'indexOf')
    at e.addRecipient (PreferencesController.js:678:35)
    at fn (eval at compile (angular.js:16548:15), <anonymous>:4:246)
    at d.<computed> [as transformChip] (angular.js:11517:22)
    at e.appendChip (angular-material.min.js?lm=1690798532:7:195163)
    at e.inputKeydown (angular-material.min.js?lm=1690798532:7:192961)
    at angular.js:1386:15
    at m.$digest (angular.js:19242:15)
    at m.$apply (angular.js:19630:13)
    at HTMLElement.<anonymous> (angular.js:29127:13)
    at xg (angular.js:3891:3)
(anonymous) @ angular.js:15697
```

**Comment by MAGICCC** [comment]
You may want to open an issue on their bugtracker. mailcow is not affliated with SOGo

**Comment by sriccio** [comment]
Yeah, I'll find where I can report this or at least check if it was already reported.

Looking at the commits, I guess this might be where it broke:
https://github.com/Alinto/sogo/commit/ba4c7a5300d7eb5ea15c13a8b3fd9b27aa4cf53a

EDIT: Well... I registered on their BT to report the issue but:

![image](https://github.com/mailcow/mailcow-dockerized/assets/5239282/9cc3da33-e766-408e-852d-6bd768bcd7e4)

Can't open an issue without first contacting them and ask for more access privileges. I guess that's it for me now.

**Comment by ftf** [comment]
Workaround until it is fixed upstream:
* Activate/click forwarding checkbox
* Use the web developer tools to remove the `disabled="disabled"` attribute from the button
* Save
* Reload the page
* Add forwarding e-mail address and save again (button is enabled now)

**Comment by IeP4nieF** [comment]
@ftf: Thank you for the hint. But sadly this doesn't work here. After using the web developer tools to remove `disabled="disabled"` the button is green, but after clicking on it nothing happens. After reloading the page the button is greyed out again.

Hopefully there will be a fix soon!

**Comment by slimbeat** [comment]
Same issue here (Version 2023-08 - Updated 24.08.2023 at about 9am), I had the issue on a newly created mailbox, but on an existing one, there was no issue with the save button.

But the workaround worked for me.

**Comment by stift-n2** [comment]
@sriccio seems to be right and this is related to the new auto-complete feature, which searches the contacts and then shows a list of possible matches.
However, if no match is found (even if a valid email address is entered) the UI does nothing and the save button remains disabled.

Therefore, another workaround is to add a new contact for each of the forward email addresses. Then it is possible to select the email from the auto-complete dropdown.

I feel like this is rather unintuitive and should be fixed upstream.

**Comment by QHivert** [comment]
Hello!
Team sogo here.
Do you still have the problem? I've noticed this bug but it should have been fixed since last week.

**Comment by stift-n2** [comment]
@QHivert Thank you for responding.
Our build is: Version 5.8.4 (@sogo-build.alinto.int 202307310509)

We just opened a report on the sogo bugtracker: https://bugs.sogo.nu/view.php?id=5850
If this was fixed last week, feel free to close it.

Could you provide a build number, where this is fixed.

**Comment by QHivert** [comment]
@stift-n2 
To be sure take the last one
Version 5.8.4 (@sogo-build.alinto.int 202309040601)
That the version that our demo server uses and I don't reproduce the problem.

**Comment by MAGICCC** [comment]
@stift-n2 
Can you try to use mailcow/sogo:pr-4897 as image? It's based on Version 5.8.4 (@sogo-build.alinto.int 202309050509)

**Comment by stift-n2** [comment]
@MAGICCC 
Perfect, mailcow/sogo:pr-4897 fixes this issue.

**Comment by QHivert** [comment]
Glad! I'll close your issue on our bts.

**Comment by milkmaker** [comment]
This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.
