### ISSUE TITLE
SOGo address book missing in UI

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#5399]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

When looking at an existing mailcow mail account in SOGo the personal and another address book (that's being shared with others) is missing on the left side.

You see the contents of the personal address book at that moment in the middle, though. Only the global address book is visible on the left side. The other address book, that is being shared with others, is missing completely and there's no simple way to access it.

If you log in with another account that has access to the shared address book within the problematic account you can see that missing address book on the left side and can access it properly.
If you try to export that address book (and only that one, all the others work) you get greeted by the `Please do not stop the stack while we are initializing the database or do other preparations.` website.

I don't see anything helpful in the logs regarding this and I don't want to post all the logs due to data privacy right now. Looking at fresh logs right after trying to access the address book overview or triggering the export didn't show anything out of order.

There's an angular.js error [ngRepeat:dupes] on the address book overview at the problematic account (and only there, other accounts don't have this). So maybe that is relevant. This is what I'll post in the logs section.

### Logs:

```plain text
angular.js:15697 Error: [ngRepeat:dupes] http://errors.angularjs.org/1.8.3/ngRepeat/dupes?[...removed due to data privacy...]
    at angular.js:99:1
    at angular.js:34028:21
    at angular.js:19130:13
    at m.$digest (angular.js:19270:23)
    at m.$apply (angular.js:19630:13)
    at angular.js:1966:9
    at Object.invoke (angular.js:5208:16)
    at c (angular.js:1964:5)
    at Wc (angular.js:1984:12)
    at Ee (angular.js:1869:5)
(anonymous) @ angular.js:15697
(anonymous) @ angular.js:11956
$digest @ angular.js:19288
$apply @ angular.js:19630
(anonymous) @ angular.js:1966
invoke @ angular.js:5208
c @ angular.js:1964
Wc @ angular.js:1984
Ee @ angular.js:1869
(anonymous) @ angular.js:36595
b @ angular.js:3587
```

### Steps to reproduce:

```plain text
No known way to reproduce this state, it must have happened sometime in the last months and updates.
```

### Which branch are you using?

master

### Operating System:

Ubuntu 22.04.2 LTS

### Server/VM specifications:

4 vCores, 8GB RAM

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

24.0.2

### docker-compose version or docker compose version:

v2.18.1

### mailcow version:

2023-08

### Reverse proxy:

none

### Logs of git diff:

```plain text
Only some changes to /postfix/main.cf
```

### Logs of iptables -L -vn:

```plain text
irrelevant
```

### Logs of ip6tables -L -vn:

```plain text
irrelevant
```

### Logs of iptables -L -vn -t nat:

```plain text
irrelevant
```

### Logs of ip6tables -L -vn -t nat:

```plain text
irrelevant
```

### DNS check:

```plain text
151.101.129.69
151.101.1.69
151.101.193.69
151.101.65.69
```

**Comment by Braintelligence** [comment]
I'd be really glad if anyone had an idea what I could look for to remove that bug.

**Comment by milkmaker** [comment]
This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by Braintelligence** [comment]
Still looking for help :)

**Comment by Braintelligence** [comment]
Sadly still having this issue, even after the latest update.

Seems like I'll have to migrate the still accessible data via some dav-tool to a new address book or something...
