### ISSUE TITLE
update.sh broke arm64

### ISSUE THREAD

**Issue by woodfairy** [mailcow/mailcow-dockerized#5596]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Hello, I just ran the update.sh script but now some containers do not have arm64e builds anymore and I cant get mailcow running again. How can I do a rollback fast?
```

### Logs:

```plain text
Cant post the logs here, is too long.

 ! rspamd-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested    0.0s
 ! watchdog-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s 


 ! dovecot-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested   0.0s
 ! postfix-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested   0.0s

 ! sogo-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested      0.0s ed0.0s
 ! dockerapi-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s ed0.0s

 ! php-fpm-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requ[+] Running 28/28

 ! sogo-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested      0.0s ed0.0s
 ! dockerapi-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s ed0.0s

 ! php-fpm-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requ[+] Running 28/28

 ! sogo-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested      0.0s ed0.0s
 ! dockerapi-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s ed0.0s

 ! php-fpm-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requ[+] Running 28/28

 ! sogo-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested      0.0s ed0.0s
 ! dockerapi-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s ed0.0s

 ! php-fpm-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requ[+] Running 28/28

 ! sogo-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested      0.0s ed0.0s
 ! dockerapi-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s ed0.0s


 ! php-fpm-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requ[+] Running 28/28


```

### Steps to reproduce:

```plain text
Run update.sh on a previously working arm64 branch
```

### Which branch are you using?

master

### Operating System:

AlmaLinux 9

### Server/VM specifications:

4 CPUs, 8GB RAM

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

 24.0.7

### docker-compose version or docker compose version:

v2.21.0

### mailcow version:

2023-11a

### Reverse proxy:

Nginx

### Logs of git diff:

```plain text
no
```

### Logs of iptables -L -vn:

```plain text
no IP issues
```

### Logs of ip6tables -L -vn:

```plain text
no IP issues
```

### Logs of iptables -L -vn -t nat:

```plain text
no IP issues
```

### Logs of ip6tables -L -vn -t nat:

```plain text
no IP issues
```

### DNS check:

```plain text
DNS is fine
```

**Comment by woodfairy** [comment]
I manually changed the image versions to the latest tag supporting arm64, now netfilter has the following exception:

```
Clearing all bans
Traceback (most recent call last):
  File "/server.py", line 558, in <module>
    clear()
  File "/server.py", line 296, in clear
    filter4_table = iptc.Table(iptc.Table.FILTER)
  File "/usr/lib/python3.10/site-packages/iptc/ip4tc.py", line 1582, in __new__
    obj._init(name, autocommit)
  File "/usr/lib/python3.10/site-packages/iptc/ip4tc.py", line 1598, in _init
    self.refresh()
  File "/usr/lib/python3.10/site-packages/iptc/ip4tc.py", line 1634, in refresh
    raise IPTCError("can't initialize %s: %s" % (self.name,
iptc.ip4tc.IPTCError: can't initialize filter: b'iptables who? (do you need to insmod?)'
```


I cannot send and receive mails atm, even though the web UI works

**Comment by iamnhx** [comment]
Use the nightly branch for arm64 support.

**Comment by woodfairy** [comment]
How do I do this? I used the feature branch but now the update broke everything, how can I safely migrate to the nightly branch without data loss?

**Comment by woodfairy** [comment]
Fixed it by backing up my data volume and checking out nightly branch, thanks @iamnhx

**Comment by MAGICCC** [comment]
You can use the --nightly flag using the update scipt

**Comment by MAGICCC** [comment]
Ay, closing this since it's fixed :)

**Comment by woodfairy** [comment]
> You can use the --nightly flag using the update scipt

This is nice for future update, thanks :)

**Comment by bi-v** [comment]
+1
