### ISSUE TITLE
Mailcow Nextcloud-cron broken on update to Nexcloud v28.0.0

### ISSUE THREAD

**Issue by thumpco** [mailcow/mailcow-dockerized#5606]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
I have 2 mailcow servers.  One that has been running Mailcow with Nextcloud for a year without issue and another I just added Nextcloud to this evening.

1) One the server I just added Nextcloud to this evening (started with v28 and behind a reverse proxy) I noticed I was getting errors.  When viewing "docker compose logs ofelia-mailcow" I see the following:

"common.go:121 ▶ ERROR [Job "nextcloud-cron" (40573c8ce6f1)] Finished in "1.374638899s", failed: true, skipped: false, error: error non-zero exit code: 1

2) On the server already running Nextcloud (no reverse proxy) I did not have this error on v27.x, but upon updating to v28, I'm now getting the same error.
```

### Logs:

```plain text
mailcowdockerized-ofelia-mailcow-1  | 2023-12-19T20:21:48.478-07:00  common.go:121 ▶ ERROR [Job "nextcloud-cron" (40573c8ce6f1)] StdOut: Sabre\DAV\Exception\Forbidden: Requested uri (/remote.php/dav/) is out of base uri (//remote.php/dav/) in /web/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php:576
mailcowdockerized-ofelia-mailcow-1  | Stack trace:
mailcowdockerized-ofelia-mailcow-1  | #0 /web/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php(542): Sabre\DAV\Server->calculateUri('/remote.php/dav...')
mailcowdockerized-ofelia-mailcow-1  | #1 /web/nextcloud/apps/photos/lib/Listener/SabrePluginAuthInitListener.php(50): Sabre\DAV\Server->getRequestUri()
mailcowdockerized-ofelia-mailcow-1  | #2 /web/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php(86): OCA\Photos\Listener\SabrePluginAuthInitListener->handle(Object(OCA\DAV\Events\SabrePluginAuthInitEvent))
mailcowdockerized-ofelia-mailcow-1  | #3 /web/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(230): OC\EventDispatcher\ServiceEventListener->__invoke(Object(OCA\DAV\Events\SabrePluginAuthInitEvent), 'OCA\\DAV\\Events\\...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
mailcowdockerized-ofelia-mailcow-1  | #4 /web/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'OCA\\DAV\\Events\\...', Object(OCA\DAV\Events\SabrePluginAuthInitEvent))
mailcowdockerized-ofelia-mailcow-1  | #5 /web/nextcloud/lib/private/EventDispatcher/EventDispatcher.php(94): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(OCA\DAV\Events\SabrePluginAuthInitEvent), 'OCA\\DAV\\Events\\...')
mailcowdockerized-ofelia-mailcow-1  | #6 /web/nextcloud/lib/private/EventDispatcher/EventDispatcher.php(106): OC\EventDispatcher\EventDispatcher->dispatch('OCA\\DAV\\Events\\...', Object(OCA\DAV\Events\SabrePluginAuthInitEvent))
mailcowdockerized-ofelia-mailcow-1  | #7 /web/nextcloud/apps/dav/lib/CalDAV/InvitationResponse/InvitationResponseServer.php(76): OC\EventDispatcher\EventDispatcher->dispatchTyped(Object(OCA\DAV\Events\SabrePluginAuthInitEvent))
mailcowdockerized-ofelia-mailcow-1  | #8 [internal function]: OCA\DAV\CalDAV\InvitationResponse\InvitationResponseServer->__construct(true)
mailcowdockerized-ofelia-mailcow-1  | #9 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(83): ReflectionClass->newInstanceArgs(Array)
mailcowdockerized-ofelia-mailcow-1  | #10 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(128): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
mailcowdockerized-ofelia-mailcow-1  | #11 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(146): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\DAV\\CalDAV\\...')
mailcowdockerized-ofelia-mailcow-1  | #12 /web/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(468): OC\AppFramework\Utility\SimpleContainer->query('OCA\\DAV\\CalDAV\\...')
mailcowdockerized-ofelia-mailcow-1  | #13 /web/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(440): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\DAV\\CalDAV\\...')
mailcowdockerized-ofelia-mailcow-1  | #14 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(96): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\DAV\\CalDAV\\...', true)
mailcowdockerized-ofelia-mailcow-1  | #15 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
mailcowdockerized-ofelia-mailcow-1  | #16 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(83): array_map(Object(Closure), Array)
mailcowdockerized-ofelia-mailcow-1  | #17 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(128): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
mailcowdockerized-ofelia-mailcow-1  | #18 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(146): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\DAV\\CalDAV\\...')
mailcowdockerized-ofelia-mailcow-1  | #19 /web/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(468): OC\AppFramework\Utility\SimpleContainer->query('OCA\\DAV\\CalDAV\\...')
mailcowdockerized-ofelia-mailcow-1  | #20 /web/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\DAV\\CalDAV\\...')
mailcowdockerized-ofelia-mailcow-1  | #21 /web/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(443): OC\ServerContainer->query('OCA\\DAV\\CalDAV\\...', true)
mailcowdockerized-ofelia-mailcow-1  | #22 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(96): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\DAV\\CalDAV\\...', true)
mailcowdockerized-ofelia-mailcow-1  | #23 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
mailcowdockerized-ofelia-mailcow-1  | #24 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(83): array_map(Object(Closure), Array)
mailcowdockerized-ofelia-mailcow-1  | #25 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(128): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
mailcowdockerized-ofelia-mailcow-1  | #26 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(146): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\UserStatus\\...')
mailcowdockerized-ofelia-mailcow-1  | #27 /web/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(468): OC\AppFramework\Utility\SimpleContainer->query('OCA\\UserStatus\\...')
mailcowdockerized-ofelia-mailcow-1  | #28 /web/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\UserStatus\\...')
mailcowdockerized-ofelia-mailcow-1  | #29 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(96): OC\ServerContainer->query('OCA\\UserStatus\\...', true)
mailcowdockerized-ofelia-mailcow-1  | #30 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
mailcowdockerized-ofelia-mailcow-1  | #31 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(83): array_map(Object(Closure), Array)
mailcowdockerized-ofelia-mailcow-1  | #32 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(128): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
mailcowdockerized-ofelia-mailcow-1  | #33 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(146): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Contacts\\Con...')
mailcowdockerized-ofelia-mailcow-1  | #34 /web/nextcloud/lib/private/ServerContainer.php(173): OC\AppFramework\Utility\SimpleContainer->query('OC\\Contacts\\Con...', true)
mailcowdockerized-ofelia-mailcow-1  | #35 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(64): OC\ServerContainer->query('OC\\Contacts\\Con...')
mailcowdockerized-ofelia-mailcow-1  | #36 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(197): OC\AppFramework\Utility\SimpleContainer->get('OC\\Contacts\\Con...')
mailcowdockerized-ofelia-mailcow-1  | #37 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(175): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
mailcowdockerized-ofelia-mailcow-1  | #38 /web/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
mailcowdockerized-ofelia-mailcow-1  | #39 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(142): Pimple\Container->offsetGet('OCP\\Contacts\\Co...')
mailcowdockerized-ofelia-mailcow-1  | #40 /web/nextcloud/lib/private/ServerContainer.php(173): OC\AppFramework\Utility\SimpleContainer->query('OCP\\Contacts\\Co...', true)
mailcowdockerized-ofelia-mailcow-1  | #41 /web/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(443): OC\ServerContainer->query('OCP\\Contacts\\Co...', true)
mailcowdockerized-ofelia-mailcow-1  | #42 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(96): OC\AppFramework\DependencyInjection\DIContainer->query('OCP\\Contacts\\Co...', true)
mailcowdockerized-ofelia-mailcow-1  | #43 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
mailcowdockerized-ofelia-mailcow-1  | #44 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(83): array_map(Object(Closure), Array)
mailcowdockerized-ofelia-mailcow-1  | #45 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(128): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
mailcowdockerized-ofelia-mailcow-1  | #46 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(146): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Circles\\Ser...')
mailcowdockerized-ofelia-mailcow-1  | #47 /web/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(468): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Circles\\Ser...')
mailcowdockerized-ofelia-mailcow-1  | #48 /web/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(440): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Circles\\Ser...')
mailcowdockerized-ofelia-mailcow-1  | #49 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(96): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Circles\\Ser...', true)
mailcowdockerized-ofelia-mailcow-1  | #50 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
mailcowdockerized-ofelia-mailcow-1  | #51 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(83): array_map(Object(Closure), Array)
mailcowdockerized-ofelia-mailcow-1  | #52 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(128): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
mailcowdockerized-ofelia-mailcow-1  | #53 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(146): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Circles\\Db\\...')
mailcowdockerized-ofelia-mailcow-1  | #54 /web/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(468): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Circles\\Db\\...')
mailcowdockerized-ofelia-mailcow-1  | #55 /web/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(440): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Circles\\Db\\...')
mailcowdockerized-ofelia-mailcow-1  | #56 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(96): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Circles\\Db\\...', true)
mailcowdockerized-ofelia-mailcow-1  | #57 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
mailcowdockerized-ofelia-mailcow-1  | #58 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(83): array_map(Object(Closure), Array)
mailcowdockerized-ofelia-mailcow-1  | #59 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(128): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
mailcowdockerized-ofelia-mailcow-1  | #60 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(146): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Circles\\Ser...')
mailcowdockerized-ofelia-mailcow-1  | #61 /web/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(468): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Circles\\Ser...')
mailcowdockerized-ofelia-mailcow-1  | #62 /web/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(440): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Circles\\Ser...')
mailcowdockerized-ofelia-mailcow-1  | #63 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(96): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Circles\\Ser...', true)
mailcowdockerized-ofelia-mailcow-1  | #64 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
mailcowdockerized-ofelia-mailcow-1  | #65 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(83): array_map(Object(Closure), Array)
mailcowdockerized-ofelia-mailcow-1  | #66 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(128): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
mailcowdockerized-ofelia-mailcow-1  | #67 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(146): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Circles\\Cro...')
mailcowdockerized-ofelia-mailcow-1  | #68 /web/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(468): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Circles\\Cro...')
mailcowdockerized-ofelia-mailcow-1  | #69 /web/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Circles\\Cro...')
mailcowdockerized-ofelia-mailcow-1  | #70 /web/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(64): OC\ServerContainer->query('OCA\\Circles\\Cro...')
mailcowdockerized-ofelia-mailcow-1  | #71 /web/nextcloud/lib/public/Server.php(55): OC\AppFramework\Utility\SimpleContainer->get('OCA\\Circles\\Cro...')
mailcowdockerized-ofelia-mailcow-1  | #72 /web/nextcloud/lib/private/BackgroundJob/JobList.php(325): OCP\Server::get('OCA\\Circles\\Cro...')
mailcowdockerized-ofelia-mailcow-1  | #73 /web/nextcloud/lib/private/BackgroundJob/JobList.php(234): OC\BackgroundJob\JobList->buildJob(Array)
mailcowdockerized-ofelia-mailcow-1  | #74 /web/nextcloud/cron.php(145): OC\BackgroundJob\JobList->getNext(false)
mailcowdockerized-ofelia-mailcow-1  | #75 {main}
mailcowdockerized-ofelia-mailcow-1  | 2023-12-19T20:21:48.478-07:00  common.go:121 ▶ ERROR [Job "nextcloud-cron" (40573c8ce6f1)] Finished in "1.374638899s", failed: true, skipped: false, error: error non-zero exit code: 1
```

### Steps to reproduce:

```plain text
1. Update mailcow's nextcloud to v28 using the web updater.
2. Output of "docker compose logs ofelia-mailcow"
```

### Which branch are you using?

master

### Operating System:

Ubuntu 22.04 LTS

### Server/VM specifications:

2 core, 4GB

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

Linode KVM

### Docker version:

24.0.7, build afdd53b

### docker-compose version or docker compose version:

v2.21.0

### mailcow version:

2023-12

### Reverse proxy:

Nginx Proxy Manager

### Logs of git diff:

```plain text
Not relevant
```

### Logs of iptables -L -vn:

```plain text
Not relevant
```

### Logs of ip6tables -L -vn:

```plain text
Not relevant
```

### Logs of iptables -L -vn -t nat:

```plain text
Not relevant
```

### Logs of ip6tables -L -vn -t nat:

```plain text
Not relevant
```

### DNS check:

```plain text
104.18.32.7
172.64.155.249
```

**Comment by thumpco** [comment]
Initially seems to fixed by editing "data/web/nextcloud/config/config.php" and removing the line: 
'overwritewebroot' => '/'

Then "docker compose down", "docker compose up -d"

Solution source: https://github.com/nextcloud/server/issues/42203
