### ISSUE TITLE
SNAT6 don't work with ip6tables

### ISSUE THREAD

**Issue by mnin** [mailcow/mailcow-dockerized#5721]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
The SNAT6 rule cannot be inserted. SNAT for IPv4 is working fine.
```

### Logs:

```plain text
# docker-compose logs netfilter-mailcow
mailcowdockerized-netfilter-mailcow-1  | Using IPTables backend
mailcowdockerized-netfilter-mailcow-1  | Clearing all bans
mailcowdockerized-netfilter-mailcow-1  | Initializing mailcow netfilter chain
mailcowdockerized-netfilter-mailcow-1  | Setting MAILCOW isolation
mailcowdockerized-netfilter-mailcow-1  | Redis is loading the dataset in memory - trying again in 3 seconds
mailcowdockerized-netfilter-mailcow-1  | Watching Redis channel F2B_CHANNEL
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x
mailcowdockerized-netfilter-mailcow-1  | Remove rule for source network 172.22.1.0/255.255.255.0 to SNAT target x.x.x.x from POSTROUTING chain at position 1
mailcowdockerized-netfilter-mailcow-1  | Error running SNAT6, retrying...
mailcowdockerized-netfilter-mailcow-1  | Error running SNAT6, retrying...
mailcowdockerized-netfilter-mailcow-1  | Error running SNAT6, retrying...
mailcowdockerized-netfilter-mailcow-1  | Error running SNAT6, retrying...
```

### Steps to reproduce:

```plain text
1. Set `SNAT6_TO_SOURCE` variable to some ipv6 address which is known in the system (e.g. added via netplan)
2. Start mailcow via `docker compose up -d`
```

### Which branch are you using?

master

### Which architecture are you using?

x86

### Operating System:

Ubuntu 22.04.6 LTS

### Server/VM specifications:

6

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

nothing

### Docker version:

25.0.3

### docker-compose version or docker compose version:

v2.24.5

### mailcow version:

2024-01e

### Reverse proxy:

Nginx

### Logs of git diff:

```plain text
diff --git a/data/conf/postfix/main.cf b/data/conf/postfix/main.cf
index 572300db..e043886a 100644
--- a/data/conf/postfix/main.cf
+++ b/data/conf/postfix/main.cf
@@ -173,3 +173,36 @@ parent_domain_matches_subdomains = debug_peer_list,fast_flush_domains,mynetworks

 # DO NOT EDIT ANYTHING BELOW #
 # Overrides #
+
+postscreen_dnsbl_sites = wl.mailspike.net=127.0.0.[18;19;20]*-2
+  hostkarma.junkemailfilter.com=127.0.0.1*-2
+  list.dnswl.org=127.0.[0..255].0*-2
+  list.dnswl.org=127.0.[0..255].1*-4
+  list.dnswl.org=127.0.[0..255].2*-6
+  list.dnswl.org=127.0.[0..255].3*-8
+  ix.dnsbl.manitu.net*2
+  bl.spamcop.net*2
+  bl.suomispam.net*2
+  hostkarma.junkemailfilter.com=127.0.0.2*3
+  hostkarma.junkemailfilter.com=127.0.0.4*2
+  hostkarma.junkemailfilter.com=127.0.1.2*1
+  backscatter.spameatingmonkey.net*2
+  bl.ipv6.spameatingmonkey.net*2
+  bl.spameatingmonkey.net*2
+  b.barracudacentral.org=127.0.0.2*7
+  bl.mailspike.net=127.0.0.2*5
+  bl.mailspike.net=127.0.0.[10;11;12]*4
+  dnsbl.sorbs.net=127.0.0.10*8
+  dnsbl.sorbs.net=127.0.0.5*6
+  dnsbl.sorbs.net=127.0.0.7*3
+  dnsbl.sorbs.net=127.0.0.8*2
+  dnsbl.sorbs.net=127.0.0.6*2
+  dnsbl.sorbs.net=127.0.0.9*2
+  zen.spamhaus.org=127.0.0.[10;11]*8
+  zen.spamhaus.org=127.0.0.[4..7]*6
+  zen.spamhaus.org=127.0.0.3*4
+  zen.spamhaus.org=127.0.0.2*3
```

### Logs of iptables -L -vn:

```plain text
Chain INPUT (policy ACCEPT 102 packets, 28572 bytes)
 pkts bytes target     prot opt in     out     source               destination
 101K   36M MAILCOW    all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
1618K 1792M MAILCOW    all  --  *      *       0.0.0.0/0            0.0.0.0/0
1617K 1792M DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0
1617K 1792M DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0
1127K  641M ACCEPT     all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
70790 4925K DOCKER     all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0
 281K  575M ACCEPT     all  --  br-mailcow !br-mailcow  0.0.0.0/0            0.0.0.0/0
69298 4841K ACCEPT     all  --  br-mailcow br-mailcow  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0
 270K 1807M ACCEPT     all  --  *      br-85ab152ebef0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
 8025  475K DOCKER     all  --  *      br-85ab152ebef0  0.0.0.0/0            0.0.0.0/0
 169K  110M ACCEPT     all  --  br-85ab152ebef0 !br-85ab152ebef0  0.0.0.0/0            0.0.0.0/0
 6198  372K ACCEPT     all  --  br-85ab152ebef0 br-85ab152ebef0  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 202 packets, 15759 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER (3 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     tcp  --  !br-85ab152ebef0 br-85ab152ebef0  0.0.0.0/0            172.18.0.2           tcp dpt:8080
 1176 66838 ACCEPT     tcp  --  !br-85ab152ebef0 br-85ab152ebef0  0.0.0.0/0            172.18.0.2           tcp dpt:443
  651 36796 ACCEPT     tcp  --  !br-85ab152ebef0 br-85ab152ebef0  0.0.0.0/0            172.18.0.2           tcp dpt:80
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.249         tcp dpt:6379
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.5           tcp dpt:8983
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.6           tcp dpt:3306
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:12345
    2   120 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:4190
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:995
    7   400 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:993
   65  3848 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:143
   17   916 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:110
  382 21160 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.8           tcp dpt:443
  283 14992 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.8           tcp dpt:80
  491 29188 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:587
  104  6000 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:465
  141  7692 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:25

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination
 281K  575M DOCKER-ISOLATION-STAGE-2  all  --  br-mailcow !br-mailcow  0.0.0.0/0            0.0.0.0/0
    0     0 DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
 169K  110M DOCKER-ISOLATION-STAGE-2  all  --  br-85ab152ebef0 !br-85ab152ebef0  0.0.0.0/0            0.0.0.0/0
  19M 8457M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-ISOLATION-STAGE-2 (3 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0
    0     0 DROP       all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
    0     0 DROP       all  --  *      br-85ab152ebef0  0.0.0.0/0            0.0.0.0/0
1418K 2184M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination
  19M 8457M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain MAILCOW (2 references)
 pkts bytes target     prot opt in     out     source               destination
   39  2220 REJECT     all  --  *      *       194.169.175.0/24     0.0.0.0/0            reject-with icmp-port-unreachable
  119  7432 REJECT     all  --  *      *       91.215.85.0/24       0.0.0.0/0            reject-with icmp-port-unreachable
    0     0 DROP       tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            0.0.0.0/0            multiport dports 3306,6379,8983,12345
```

### Logs of ip6tables -L -vn:

```plain text
Chain INPUT (policy ACCEPT 8776 packets, 6951K bytes)
 pkts bytes target     prot opt in     out     source               destination
 8846 6955K MAILCOW    all      *      *       ::/0                 ::/0

Chain FORWARD (policy DROP 14 packets, 784 bytes)
 pkts bytes target     prot opt in     out     source               destination
 349K  553M DOCKER-USER  all      *      *       ::/0                 ::/0
 351K  554M MAILCOW    all      *      *       ::/0                 ::/0
 351K  554M DOCKER-ISOLATION-STAGE-1  all      *      *       ::/0                 ::/0
 292K  479M ACCEPT     all      *      br-mailcow  ::/0                 ::/0                 ctstate RELATED,ESTABLISHED
21762 1566K DOCKER     all      *      br-mailcow  ::/0                 ::/0
37263   73M ACCEPT     all      br-mailcow !br-mailcow  ::/0                 ::/0
21150 1515K ACCEPT     all      br-mailcow br-mailcow  ::/0                 ::/0
    0     0 ACCEPT     all      *      docker0  ::/0                 ::/0                 ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all      *      docker0  ::/0                 ::/0
    0     0 ACCEPT     all      docker0 !docker0  ::/0                 ::/0
    0     0 ACCEPT     all      docker0 docker0  ::/0                 ::/0

Chain OUTPUT (policy ACCEPT 8097 packets, 6400K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination
  465 39066 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::c  tcp dpt:443
   31  2416 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::c  tcp dpt:80
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::b  tcp dpt:4190
   95  7980 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::b  tcp dpt:993
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::b  tcp dpt:995
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::b  tcp dpt:110
    5   420 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::b  tcp dpt:143
    4   320 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::11  tcp dpt:25
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::11  tcp dpt:465
    2   168 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::11  tcp dpt:587

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER-ISOLATION-STAGE-2  all      docker0 !docker0  ::/0                 ::/0
37119   73M DOCKER-ISOLATION-STAGE-2  all      br-mailcow !br-mailcow  ::/0                 ::/0
 349K  553M RETURN     all      *      *       ::/0                 ::/0

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all      *      docker0  ::/0                 ::/0
    0     0 DROP       all      *      br-mailcow  ::/0                 ::/0
37119   73M RETURN     all      *      *       ::/0                 ::/0

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination
6550K 3746M RETURN     all      *      *       ::/0                 ::/0

Chain MAILCOW (2 references)
 pkts bytes target     prot opt in     out     source               destination
```

### Logs of iptables -L -vn -t nat:

```plain text
Chain PREROUTING (policy ACCEPT 146K packets, 11M bytes)
 pkts bytes target     prot opt in     out     source               destination
85460 4502K DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 14469 packets, 698K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 392 packets, 29069 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 72831 packets, 5054K bytes)
 pkts bytes target     prot opt in     out     source               destination
55428 4721K SNAT       all  --  *      *       172.22.1.0/24       !172.22.1.0/24        /* 1707410592 */ to:x.x.x.x
    0     0 MASQUERADE  all  --  *      !br-mailcow  172.22.1.0/24        0.0.0.0/0
    0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0
  313 18780 MASQUERADE  all  --  *      !br-85ab152ebef0  172.18.0.0/16        0.0.0.0/0
    0     0 MASQUERADE  tcp  --  *      *       172.18.0.2           172.18.0.2           tcp dpt:8080
    0     0 MASQUERADE  tcp  --  *      *       172.18.0.2           172.18.0.2           tcp dpt:443
    0     0 MASQUERADE  tcp  --  *      *       172.18.0.2           172.18.0.2           tcp dpt:80
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.249         172.22.1.249         tcp dpt:6379
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.5           172.22.1.5           tcp dpt:8983
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.6           172.22.1.6           tcp dpt:3306
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:12345
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:4190
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:995
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:993
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:143
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:110
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.8           172.22.1.8           tcp dpt:443
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.8           172.22.1.8           tcp dpt:80
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.253         172.22.1.253         tcp dpt:587
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.253         172.22.1.253         tcp dpt:465
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.253         172.22.1.253         tcp dpt:25

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination
    1    60 RETURN     all  --  br-mailcow *       0.0.0.0/0            0.0.0.0/0
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0
    0     0 RETURN     all  --  br-85ab152ebef0 *       0.0.0.0/0            0.0.0.0/0
    0     0 DNAT       tcp  --  !br-85ab152ebef0 *       0.0.0.0/0            127.0.0.1            tcp dpt:8080 to:172.18.0.2:8080
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:7654 to:172.22.1.249:6379
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:18983 to:172.22.1.5:8983
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:13306 to:172.22.1.6:3306
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:19991 to:172.22.1.250:12345
    2   120 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            x.x.x.x       tcp dpt:4190 to:172.22.1.250:4190
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            x.x.x.x       tcp dpt:995 to:172.22.1.250:995
    7   400 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            x.x.x.x       tcp dpt:993 to:172.22.1.250:993
   65  3848 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            x.x.x.x       tcp dpt:143 to:172.22.1.250:143
   17   916 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            x.x.x.x       tcp dpt:110 to:172.22.1.250:110
  383 21220 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            x.x.x.x       tcp dpt:443 to:172.22.1.8:443
  285 15092 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            x.x.x.x       tcp dpt:80 to:172.22.1.8:80
  588 35008 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            x.x.x.x       tcp dpt:587 to:172.22.1.253:587
  381 22620 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            x.x.x.x       tcp dpt:465 to:172.22.1.253:465
  141  7692 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            x.x.x.x       tcp dpt:25 to:172.22.1.253:25
```

### Logs of ip6tables -L -vn -t nat:

```plain text
Chain PREROUTING (policy ACCEPT 23284 packets, 2112K bytes)
 pkts bytes target     prot opt in     out     source               destination
93121 7830K DOCKER     all      *      *       ::/0                 ::/0                 ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 410 packets, 34371 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 33 packets, 2816 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER     all      *      *       ::/0                !::1                  ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 9069 packets, 728K bytes)
 pkts bytes target     prot opt in     out     source               destination
14549 1414K MASQUERADE  all      *      !br-mailcow  fd4d:6169:6c63:6f77::/64  ::/0
    0     0 MASQUERADE  all      *      docker0  ::/0                 ::/0                 ADDRTYPE match dst-type LOCAL
    0     0 MASQUERADE  all      *      br-mailcow  ::/0                 ::/0                 ADDRTYPE match dst-type LOCAL
    0     0 MASQUERADE  all      *      !docker0  fd00:dead:beef:c0::/80  ::/0
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::b  fd4d:6169:6c63:6f77::b  tcp dpt:4190
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::b  fd4d:6169:6c63:6f77::b  tcp dpt:995
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::b  fd4d:6169:6c63:6f77::b  tcp dpt:993
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::b  fd4d:6169:6c63:6f77::b  tcp dpt:143
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::b  fd4d:6169:6c63:6f77::b  tcp dpt:110
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::c  fd4d:6169:6c63:6f77::c  tcp dpt:443
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::c  fd4d:6169:6c63:6f77::c  tcp dpt:80
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::11  fd4d:6169:6c63:6f77::11  tcp dpt:587
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::11  fd4d:6169:6c63:6f77::11  tcp dpt:465
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::11  fd4d:6169:6c63:6f77::11  tcp dpt:25

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 RETURN     all      docker0 *       ::/0                 ::/0
   11   880 RETURN     all      br-mailcow *       ::/0                 ::/0
  467 39226 DNAT       tcp      !br-mailcow *       ::/0                 xxxx::xxxx  tcp dpt:443 to:[fd4d:6169:6c63:6f77::c]:443
   31  2416 DNAT       tcp      !br-mailcow *       ::/0                 xxxx::xxxx  tcp dpt:80 to:[fd4d:6169:6c63:6f77::c]:80
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 xxxx::xxxx  tcp dpt:4190 to:[fd4d:6169:6c63:6f77::b]:4190
   95  7980 DNAT       tcp      !br-mailcow *       ::/0                 xxxx::xxxx  tcp dpt:993 to:[fd4d:6169:6c63:6f77::b]:993
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 xxxx::xxxx  tcp dpt:995 to:[fd4d:6169:6c63:6f77::b]:995
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 xxxx::xxxx  tcp dpt:110 to:[fd4d:6169:6c63:6f77::b]:110
    5   420 DNAT       tcp      !br-mailcow *       ::/0                 xxxx::xxxx  tcp dpt:143 to:[fd4d:6169:6c63:6f77::b]:143
    4   320 DNAT       tcp      !br-mailcow *       ::/0                 xxxx::xxxx  tcp dpt:25 to:[fd4d:6169:6c63:6f77::11]:25
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 xxxx::xxxx  tcp dpt:465 to:[fd4d:6169:6c63:6f77::11]:465
    2   168 DNAT       tcp      !br-mailcow *       ::/0                 xxxx::xxxx  tcp dpt:587 to:[fd4d:6169:6c63:6f77::11]:587
```

### DNS check:

```plain text
104.18.32.7
172.64.155.249
```

**Comment by mnin** [comment]
I was able to add the rule manually on the host system:

```shell
ip6tables -t nat -I POSTROUTING 1 -s fd4d:6169:6c63:6f77::/64 ! -d fd4d:6169:6c63:6f77::/64 -j SNAT --to-source 0::0
```

Curl from the Postfix container now temporarily uses the correct IPv6 address as the source.

**Comment by iiegn** [comment]
i'm seeing the same behavior, with the following stack track:
```
netfilter-mailcow-1  | Error running SNAT6, retrying...
netfilter-mailcow-1  | Traceback (most recent call last):
netfilter-mailcow-1  |   File "/app/modules/IPTables.py", line 184, in snat6
netfilter-mailcow-1  |     new_rule = self.getSnat6Rule(snat_target, source)
netfilter-mailcow-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netfilter-mailcow-1  |   File "/app/modules/IPTables.py", line 217, in getSnat6Rule
netfilter-mailcow-1  |     target = rule.create_target("SNAT")
netfilter-mailcow-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
netfilter-mailcow-1  |   File "/usr/lib/python3.11/site-packages/iptc/ip4tc.py", line 1002, in create_target
netfilter-mailcow-1  |     target = Target(self, name=name, revision=revision, goto=goto)
netfilter-mailcow-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netfilter-mailcow-1  |   File "/usr/lib/python3.11/site-packages/iptc/ip4tc.py", line 728, in __init__
netfilter-mailcow-1  |     raise XTablesError("can't find target %s" % (name))
netfilter-mailcow-1  | iptc.errors.XTablesError: can't find target SNAT
```
