### ISSUE TITLE
Sogo calendar in Japanese DatePicker not work normally

### ISSUE THREAD

**Issue by kusime** [mailcow/mailcow-dockerized#5787]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Can not pick the date when SOGo running in Japanese
```

### Logs:

```plain text
angular.js:15697 TypeError: e.getFullYear is not a function
    at n.getDateId (angular-material.min.js?lm=1707403761:7:219527)
    at n.changeSelectedDate (angular-material.min.js?lm=1707403761:7:217974)
    at angular-material.min.js?lm=1707403761:7:222639
    at m.$broadcast (angular.js:19850:15)
    at e.$render (angular-material.min.js?lm=1707403761:7:216595)
    at t.initialize (angular-material.min.js?lm=1707403761:7:221411)
    at Object.link (angular-material.min.js?lm=1707403761:7:220645)
    at angular.js:1391:15
    at Ca (angular.js:11376:9)
    at p (angular.js:10695:11)
(anonymous) @ angular.js:15697
(anonymous) @ angular.js:11956
$broadcast @ angular.js:19852
e.$render @ angular-material.min.js?lm=1707403761:7
t.initialize @ angular-material.min.js?lm=1707403761:7
link @ angular-material.min.js?lm=1707403761:7
(anonymous) @ angular.js:1391
Ca @ angular.js:11376
p @ angular.js:10695
g @ angular.js:9942
(anonymous) @ angular.js:9807
(anonymous) @ angular.js:10221
d @ angular.js:9985
m @ angular.js:10745
(anonymous) @ angular.js:34783
r @ angular.js:388
(anonymous) @ angular.js:34782
$digest @ angular.js:19270
$apply @ angular.js:19630
(anonymous) @ angular.js:29127
xg @ angular.js:3891
d @ angular.js:3879
5angular.js:15697 TypeError: t.getDate is not a function
    at Object.isSameDay (angular-material.min.js?lm=1707403761:7:235280)
    at he.buildDateCell (angular-material.min.js?lm=1707403761:7:224779)
    at he.buildCalendarForMonth (angular-material.min.js?lm=1707403761:7:226534)
    at he.generateContent (angular-material.min.js?lm=1707403761:7:223752)
    at angular-material.min.js?lm=1707403761:7:29792
    at b.$digest (angular.js:19270:23)
    at r.updateBlock_ (angular-material.min.js?lm=1707403761:7:358276)
    at r.virtualRepeatUpdate_ (angular-material.min.js?lm=1707403761:7:357056)
    at r.containerUpdated (angular-material.min.js?lm=1707403761:7:356128)
    at t.updateSize (angular-material.min.js?lm=1707403761:7:351710)
(anonymous) @ angular.js:15697
(anonymous) @ angular.js:11956
$digest @ angular.js:19288
r.updateBlock_ @ angular-material.min.js?lm=1707403761:7
r.virtualRepeatUpdate_ @ angular-material.min.js?lm=1707403761:7
r.containerUpdated @ angular-material.min.js?lm=1707403761:7
t.updateSize @ angular-material.min.js?lm=1707403761:7
(anonymous) @ angular.js:1392
(anonymous) @ angular-material.min.js?lm=1707403761:7
(anonymous) @ angular.js:1391
requestAnimationFrame (async)
f @ angular.js:18424
t @ angular-material.min.js?lm=1707403761:7
invoke @ angular.js:5208
S.instance @ angular.js:11814
p @ angular.js:10627
g @ angular.js:9942
g @ angular.js:9945
p @ angular.js:10689
g @ angular.js:9942
(anonymous) @ angular.js:9807
(anonymous) @ angular.js:10221
d @ angular.js:9985
m @ angular.js:10745
(anonymous) @ angular.js:34783
r @ angular.js:388
(anonymous) @ angular.js:34782
$digest @ angular.js:19270
$apply @ angular.js:19630
(anonymous) @ angular.js:29127
xg @ angular.js:3891
d @ angular.js:3879
angular-material.min.js?lm=1707403761:7 Uncaught TypeError: t.getFullYear is not a function
    at Object.getMonthDistance (angular-material.min.js?lm=1707403761:7:235343)
    at t.getSelectedMonthIndex (angular-material.min.js?lm=1707403761:7:221512)
    at fn (eval at compile (angular.js:16548:15), <anonymous>:4:198)
    at m.$eval (angular.js:19523:16)
    at r.virtualRepeatUpdate_ (angular-material.min.js?lm=1707403761:7:357677)
    at r.containerUpdated (angular-material.min.js?lm=1707403761:7:356128)
    at t.updateSize (angular-material.min.js?lm=1707403761:7:351710)
    at angular.js:1392:15
    at t.<anonymous> (angular-material.min.js?lm=1707403761:7:349538)
    at angular.js:1391:15
```

### Steps to reproduce:

```plain text
1. Change the webmail application lang to Japanese
2. Try to create new event
3. The error will appear
```

### Which branch are you using?

master

### Which architecture are you using?

x86

### Operating System:

Ubuntu 23.10

### Server/VM specifications:

16G/4

### Is Apparmor, SELinux or similar active?

yes

### Virtualization technology:

KVM

### Docker version:

24.0.5

### docker-compose version or docker compose version:

Docker Compose version 2.20.2+ds1-0ubuntu1

### mailcow version:

2024-02

### Reverse proxy:

Nginx

### Logs of git diff:

```plain text
No
```

### Logs of iptables -L -vn:

```plain text
May be fontend error. MailServer work fine . and can send and receive mail normally
```

### Logs of ip6tables -L -vn:

```plain text
May be fontend error. MailServer work fine . and can send and receive mail normally
```

### Logs of iptables -L -vn -t nat:

```plain text
May be fontend error. MailServer work fine . and can send and receive mail normally
```

### Logs of ip6tables -L -vn -t nat:

```plain text
May be fontend error. MailServer work fine . and can send and receive mail normally
```

### DNS check:

```plain text
docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254
172.64.155.249
104.18.32.7
```

**Comment by kusime** [comment]
![image](https://github.com/mailcow/mailcow-dockerized/assets/60957601/83921caa-b625-4aff-907f-02b5ea8820b0)

**Comment by kusime** [comment]
This issuse only happend in Japanese , In other language will not happend
![image](https://github.com/mailcow/mailcow-dockerized/assets/60957601/bad51510-41df-465e-978b-153929eaa11a)

**Comment by MAGICCC** [comment]
You have to ask on Sogos bugtracker: https://bugs.sogo.nu

mailcow is not dev of Sogo
