### ISSUE TITLE
acme-mailcow created verification file name with lower case symbols, but checked file name contains only uppercase

### ISSUE THREAD

**Issue by LxanderUA** [mailcow/mailcow-dockerized#5937]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
receiving ValueError: Challenge did not pass for mydomain
I think because created filename contains lower case letters (file is created and available) but validated filename contains only uppercase letter.
Changed in log domain to mydomain.com and IP to 0.0.0.0
```

### Logs:

```plain text
acme-mailcow-1  | Creating new order...
acme-mailcow-1  | Order created!
acme-mailcow-1  | Verifying mydomain.com...
acme-mailcow-1  | Traceback (most recent call last):
acme-mailcow-1  |   File "/usr/bin/acme-tiny", line 8, in <module>
acme-mailcow-1  |     sys.exit(main())
acme-mailcow-1  |              ^^^^^^
acme-mailcow-1  |   File "/usr/lib/python3.12/site-packages/acme_tiny.py", line 195, in main
acme-mailcow-1  |     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact, check_port=args.check_port)
acme-mailcow-1  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
acme-mailcow-1  |   File "/usr/lib/python3.12/site-packages/acme_tiny.py", line 153, in get_crt
acme-mailcow-1  |     raise ValueError("Challenge did not pass for {0}: {1}".format(domain, authorization))
acme-mailcow-1  | ValueError: Challenge did not pass for mydomain.com: {'identifier': {'type': 'dns', 'value': 'mydomain.com'}, 'status': 'invalid', 'expires': '2024-07-12T16:41:15Z', 'challenges': [{'type': 'http-01', 'url': 'https://acme-v02.api.letsencrypt.org/acme/chall-v3/373082688957/n1ebyw', 'status': 'invalid', 'validated': '2024-07-05T16:41:16Z', 'error': {'type': 'urn:ietf:params:acme:error:unauthorized', 'detail': '0.0.0.0: Invalid response from https://mydomain.com/.WELL-KNOWN/ACME-CHALLENGE/YGX7DYDW0GBLSADXFK4TGQV3CGFBOXSKDP7JXMJFJ40: 404', 'status': 403}, 'token': 'YGx7dYDW0GblSadXFk4TGqV3CGFboxSkDP7JXmjFj40', 'validationRecord': [{'url': 'http://mydomain.com/.well-known/acme-challenge/YGx7dYDW0GblSadXFk4TGqV3CGFboxSkDP7JXmjFj40', 'hostname': 'mydomain.com', 'port': '80', 'addressesResolved': ['0.0.0.0'], 'addressUsed': '0.0.0.0'}, {'url': 'https://mydomain.com/.WELL-KNOWN/ACME-CHALLENGE/YGX7DYDW0GBLSADXFK4TGQV3CGFBOXSKDP7JXMJFJ40', 'hostname': 'mydomain.com', 'port': '443', 'addressesResolved': ['0.0.0.0'], 'addressUsed': '0.0.0.0'}]}]}
acme-mailcow-1  | Fri Jul  5 11:41:19 CDT 2024 - Failed to obtain certificate /var/lib/acme/mydomain.com/cert.pem for domains 'mydomain.com'
acme-mailcow-1  | OK
acme-mailcow-1  | Fri Jul  5 11:41:19 CDT 2024 - Some errors occurred, retrying in 30 minutes...
acme-mailcow-1  | OK
```

### Steps to reproduce:

```plain text
docker compose restart acme-mailcow
docker compose logs --tail=200 -f acme-mailcow
```

### Which branch are you using?

master

### Which architecture are you using?

ARM64 (aarch64)

### Operating System:

Ubuntu 22.04 LTS

### Server/VM specifications:

8

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

proxmox

### Docker version:

27.0.3

### docker-compose version or docker compose version:

v2.28.1

### mailcow version:

2024-06a

### Reverse proxy:

Apache

### Logs of git diff:

```plain text
diff --git a/data/assets/ssl-example/cert.pem b/data/assets/ssl-example/cert.pem
diff --git a/data/assets/ssl-example/key.pem b/data/assets/ssl-example/key.pem
diff --git a/data/conf/postfix/main.cf b/data/conf/postfix/main.cf
index 6a87f2ec..9179cf07 100644
--- a/data/conf/postfix/main.cf
+++ b/data/conf/postfix/main.cf
@@ -173,3 +173,30 @@ parent_domain_matches_subdomains = debug_peer_list,fast_flush_domains,mynetworks

 # DO NOT EDIT ANYTHING BELOW #
 # Overrides #
+
+postscreen_dnsbl_sites = wl.mailspike.net=127.0.0.[18;19;20]*-2
+  hostkarma.junkemailfilter.com=127.0.0.1*-2
+  list.dnswl.org=127.0.[0..255].0*-2
+  list.dnswl.org=127.0.[0..255].1*-4
+  list.dnswl.org=127.0.[0..255].2*-6
+  list.dnswl.org=127.0.[0..255].3*-8
+  ix.dnsbl.manitu.net*2
+  bl.spamcop.net*2
+  bl.suomispam.net*2
+  hostkarma.junkemailfilter.com=127.0.0.2*3
+  hostkarma.junkemailfilter.com=127.0.0.4*2
+  hostkarma.junkemailfilter.com=127.0.1.2*1
+  backscatter.spameatingmonkey.net*2
+  bl.ipv6.spameatingmonkey.net*2
+  bl.spameatingmonkey.net*2
+  b.barracudacentral.org=127.0.0.2*7
+  bl.mailspike.net=127.0.0.2*5
+  bl.mailspike.net=127.0.0.[10;11;12]*4
+  zen.spamhaus.org=127.0.0.[10;11]*8
+  zen.spamhaus.org=127.0.0.[4..7]*6
+  zen.spamhaus.org=127.0.0.3*4
+  zen.spamhaus.org=127.0.0.2*3
+
+# User Overrides
+myhostname = mydomain.com
```

### Logs of iptables -L -vn:

```plain text
no
```

### Logs of ip6tables -L -vn:

```plain text
no
```

### Logs of iptables -L -vn -t nat:

```plain text
no
```

### Logs of ip6tables -L -vn -t nat:

```plain text
no
```

### DNS check:

```plain text
172.64.155.249
104.18.32.7
```

**Comment by LxanderUA** [comment]
I believe it was silently fixed. The issue has gone.
