### ISSUE TITLE
tracebacks in dockerapi

### ISSUE THREAD

**Issue by pschiffe** [mailcow/mailcow-dockerized#765]
Occasionally I see in docker logs of `mailcow/dockerapi:1.2`:
```
[2017-11-21 23:08:14,810] ERROR in app: Exception on /containers/json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/server.py", line 22, in get
    return jsonify(type='danger', msg=e)
  File "/usr/local/lib/python2.7/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/usr/local/lib/python2.7/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/local/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/local/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python2.7/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: APIError(HTTPError(u'400 Client Error: Bad Request for url: http+docker://localunixsocket/v1.30/containers/json?all=1&limit=-1&trunc_cmd=0&size=0',),) is not JSON serializable
172.22.1.8 - - [21/Nov/2017 23:08:14] "GET /containers/json HTTP/1.1" 500 -
```

My docker-compose part of the dockerapi:
```
    dockerapi-mailcow:
      image: mailcow/dockerapi:1.2
      restart: always
      build: ./data/Dockerfiles/dockerapi
      oom_score_adj: -10
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /etc/localtime:/etc/localtime:ro
      security_opt:
        - label:disable
      networks:
        mailcow-network:
          aliases:
            - dockerapi
```

It's docker on centos 7:
```
# docker info
Containers: 15
 Running: 15
 Paused: 0
 Stopped: 0
Images: 36
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker--vg-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 11.92 GB
 Data Space Total: 31.82 GB
 Data Space Available: 19.9 GB
 Metadata Space Used: 3.297 MB
 Metadata Space Total: 33.55 MB
 Metadata Space Available: 30.26 MB
 Thin Pool Minimum Free Space: 3.181 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-693.5.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 2
Total Memory: 7.639 GiB
Name: some.host.url
ID: BLAH:BLAH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)
```

**Comment by pschiffe** [comment]
I see this traceback  when trying to restart sogo from mailcow admin, it doesn't work, fails with an error now (since docker api container is running). I have to restart sogo manually when I add a new domain.

**Comment by pschiffe** [comment]
I think I know what's the problem now:
```
$ curl --unix-socket /var/run/docker.sock http://localunixsocket/v1.30/containers/json
{"message":"client is newer than server (client API version: 1.30, server API version: 1.24)"}
```

This simple patch of `server.py` in dockerapi container fixed it for me:
```
- docker_client = docker.DockerClient(base_url='unix://var/run/docker.sock')
+ docker_client = docker.DockerClient(base_url='unix://var/run/docker.sock', version='auto')
```

Do you think you could update the dockerapi image? That would help a lot. Thank you.
