### ISSUE TITLE
ActiveSync validation fails

### ISSUE THREAD

**Issue by TiiFuchs** [mailcow/mailcow-dockerized#926]
I'm running mailcow under 8080/8443 but have a reverse proxy on 443 for different domains.
I figured so far, that the AutoDiscover Feature works and outputs the MAILCOW_HOSTNAME (which is okay) but it guesses the port from the HTTP_HOST server variable in vars.inc.php. So I changed that using the variable $https_port and since then the AutoDiscover XML outputs the correct host/port.

I tried to test ActiveSync then, but realized on https://testconnectivity.microsoft.com/ that it's using port 443 anyway. Even if it's posting this: 

> Exchange ActiveSync URL https://{MAILCOW_HOSTNAME}:8443/Microsoft-Server-ActiveSync was validated successfully.

And since the mailcow_host:443 is not routed to mailcow the ssl certificate is (of course) invalid. And even if it was, there would be no answer by mailcow.

Does ActiveSync support ports other than 443? Since obviously it is ignoring the other port.

**Comment by TiiFuchs** [comment]
I just made that certificate on :443 valid and looked at the steps after that.

Seems like it's connecting anyway to the (correct) port 8443 for ActiveSync:

> Testing HTTP Authentication Methods for URL https://{MAILCOW_HOSTNAME}:8443/Microsoft-Server-ActiveSync.
> The HTTP authentication test failed.

The additional details give me the following:

```
Exception details:
Message: The underlying connection was closed: An unexpected error occurred on a send.
Type: System.Net.WebException
Stack trace:
at System.Net.HttpWebRequest.GetResponse()
at Microsoft.Exchange.Tools.ExRca.Extensions.RcaHttpRequest.GetResponse()
Exception details:
Message: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
Type: System.IO.IOException
Stack trace:
at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
at System.Net.ConnectStream.WriteHeaders(Boolean async)
Exception details:
Message: An existing connection was forcibly closed by the remote host
Type: System.Net.Sockets.SocketException
Stack trace:
at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
Elapsed Time: 131 ms.
```

Looks like there is a bug somewhere anyway...

**Comment by TiiFuchs** [comment]
It should be noted, that a manual Exchange account entry on iOS works as long as you specify {MAILCOW_HOSTNAME}:8443 as Server (including the port).

But the same thing with autodiscover seems not to work and the testconnectivity tool from Microsoft fails too.
